### ISSUE TITLE
`cd` not working in `webcontainer/api`

### ISSUE THREAD

**Issue by privatenumber** [stackblitz/webcontainer-core#1008]
### Describe the bug

When running `cd` via `#spawn`, it doesn't actually update the current working directory.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-3gkehy?file=main.js

### Steps to reproduce

Go to the reproduction and see the error in the JS console.

The reproduction does the following, where `exec` runs `#spawn`:
```js
const pwd1 = await exec('pwd');

await exec('mkdir', ['test']);
await exec('cd', ['test']);

const pwd2 = await exec('pwd');

if (pwd1.output === pwd2.output) {
  throw new Error(
    `cd failed - pwd before and after \`cd\` is identical: ${pwd2.output}.`
  );
}
```

Running `pwd` after running `cd` should show the new directory.

### Expected behavior

For `cd` to work. It works on StackBlitz, so confused why it doesn't work here.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

StackBlitz

### Additional context

(Very cool that WebContainers is running in WebContainers!)

**Comment by Nemikolh** [comment]
Hi @privatenumber ! :wave: 

This is expected behaviour! I think it's best to see `WebContainer` not as a `shell` but as a mini operating system. If you have this mindset then there's no such thing as a changing the `cwd` for an OS, rather here what you observe is that:
* You first spawn a process (`pwd`) that has no PPID and get started with a default working directory (`/home/<workdirName>`)
* You then start a second process (unrelated). Interestingly enough, `cd` is a shell builtin so you should expect an error. However because we try to find a good middle ground between what unixy OSes do, we actually have a dummy `/usr/bin/cd` executable that does nothing. You can see that by running `command cd` in a shell on stackblitz vs in `zsh` on Linux. The former works while the latter complains about a missing command `cd`.
* Finally you spawn another `pwd` process which does the same as when the first was executed.

How could you get the what you would expect? 

By running everything in our shell JSH of course! (not to be confused with the npm package of the same name):

```ts
const pwd1 = await exec('jsh', ['-c', 'pwd; mkdir test; cd test; pwd']);
console.log(pwd1.output)
```

Let me know if you have any other questions :smiley:

**Comment by privatenumber** [comment]
Thanks so much! That's exactly what I was looking for.

Really appreciate the careful explanation.

BTW You may have meant `which cd` doesn't work in a shell. `command cd` works for me on zsh.

**Comment by Nemikolh** [comment]
> `command cd` works for me on zsh.

Oh interesting! Maybe my version of `zsh` works differently. Which distribution of Linux are you using?

I'm on Ubuntu and I have:

```
➜  ~ command cd
zsh: command not found: cd
➜  ~ zsh --version
zsh 5.8.1 (x86_64-ubuntu-linux-gnu)
```

**Comment by Nemikolh** [comment]
Oh but you're on macOS! I think for you, you have a `cd` binary. You can check with `whence -ac cd` which should list a path in addition to the shell built-in.

**Comment by privatenumber** [comment]
Ah yes, you're right! TIL

```sh
➜  ~ whence -ac cd
cd: shell built-in command
/usr/bin/cd
```
