### ISSUE TITLE
`fs` API to mock Node.js on Web Container instance

### ISSUE THREAD

**Issue by privatenumber** [stackblitz/webcontainer-core#1026]
**Is your feature request related to a problem? Please describe:**

The current fs API on Web Containers is limited and can't be used with Node.js libraries that expect a filesystem (e.g. in-place of [memfs](https://github.com/streamich/memfs)).

For instance, when using `esbuild-wasm` or Webpack in the frontend, I should be able to spin-up a Web Container and pass it in as the file-system.

Instead, I currently, need to spin-up an instance, run `npm install esbuild-wasm` (which adds a lot of overhead), then run a build within the WebContainer.

**Describe the solution you'd like:**

An `fs`-like API should be implemented on the Web Container instance, allowing integration with frontend tools that rely on a filesystem (e.g., as an alternative to [memfs](https://github.com/streamich/memfs)):

```ts
import { WebContainer } from '@webcontainer/api';

const webcontainerInstance = await WebContainer.boot();

// webcontainerInstance.fs.statSync()
// webcontainerInstance.fs.promises.stat()

// globalThis.fs = webcontainerInstance.fs // To override the `fs` for esbuild-wasm
```

**Describe alternatives you've considered:**

**Additional context:**

**Comment by jrvidal** [comment]
FWIW, providing a full Node.js-compatible fs API in `WebContainer#fs` is a non-goal. The purpose of that "file system" is to help integration with embedders/editors, not to act like a full shim.

If `npm install esbuild-wasm` is too much overhead for your use case, you could maybe experiment with calling `WebContainer#mount()` with a static "bundle" under your control, so you bypass the installation process.

**Comment by privatenumber** [comment]
Is there overhead to calling esbuild-wasm inside of a WebContainer compared to outside?

**Comment by Nemikolh** [comment]
It's a good question and a bit tricky to answer simply. In theory one could hand-tune an ad-hoc solution for your problem that would end up being much faster than using WebContainer on both memory consumption and speed.

Now if we try to stay pragmatical, here are some aspects worth considering that could affect speed:

 * If you intend to run `esbuild-wasm` once every now and then on a big chunk, then the overhead would likely not be noticeable because most of the time spent would be within the WASM part of `esbuild-wasm` which is the same in both cases.

 * If you intend to run `esbuild-wasm` on every keystroke on a small chunk, then my guess is that the overhead would become more noticeable, however:
    * To beat WebContainer you would have to do some of the things we do to be fast, like pooling Workers for instance
    * You would be able to cache WASM modules (I don't think we do atm)
    * You would loose on future perf improvements we make to WebContainer.

Now in terms of memory usage, right now the overhead is definitely there. _(We have ideas on improving this though, it's not a hard limitation)_

**Comment by privatenumber** [comment]
Thank you for the detailed response. I appreciate the performance insights.

I'll continue to use `esbuild-wasm` inside the WebContainer and expect performance improvements in the future.

To minimize overhead, I'll try to use `mount()` instead of `npm install`.
