### ISSUE TITLE
Web Container fails to start due to CORs and Cross origin Embed errors

### ISSUE THREAD

**Issue by mhartington** [stackblitz/webcontainer-core#1041]
### Describe the bug

I know Safari support is not official, but figured it was worth mentioning.

When loading a basic starter web container, it fails to boot due to various Cross origin errors.

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-f52gv1?file=README.md

### Steps to reproduce

1. Open [this link](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-f52gv1?file=README.md) in Safari
2. Open the devtools and see the errors

### Expected behavior

The necessary headers should be set in order to support SharedArrayBuffer.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1402" alt="Screenshot 2023-04-22 at 6 42 52 PM" src="https://user-images.githubusercontent.com/2835826/233810640-4ba767ff-bf0a-4a4a-9c42-ac9245f72645.png">

### Platform

```
Browser name  = Safari
Full version  = 16.4
Major version = 16
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.4 Safari/605.1.15
performance.memory = undefined
Hash = 95b70c8d
```

**Comment by SamVerschueren** [comment]
Hey @mhartington 👋 . Thanks for reaching out!

The problem here is that Safari has a bug (which is fixed in Safari TP in the mean time) and was reported by us a while ago https://bugs.webkit.org/show_bug.cgi?id=254065.

Basically, if an `html` file with COEP/CORP setting is cached by Safari, those headers are not taken into account when that file is retrieved from disk cache.

I thought we worked around that issue for now, but apparently there's still something wrong here. So looking into it right now and I will keep you posted.

You should notice that forking the project should make it work again. Until you entirely quit Safari and load that forked project again, then Safari breaks 🤦 .

Anyways, I'll keep you posted!

**Comment by SamVerschueren** [comment]
We've implemented a fix and just deployed it. I verified and it works correctly now on my end. Let us know if you still run into issues.
