### ISSUE TITLE
HttpError: Failed to fetch dependencies: @matrix-org/olm@3.2.14

### ISSUE THREAD

**Issue by crummy** [stackblitz/webcontainer-core#1056]
### Describe the bug

I'm testing out `hydrogen-view-sdk`. I started a vite vanilla+ts project, then tried to add the dependency, but I get a "Failed to fetch" error. 

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-wxouem

### Steps to reproduce

In the terminal I ran `npm install hydrogen-view-sdk`. Here's my output:
```
❯ npm install hydrogen-view-sdk
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/4] �  Resolving dependencies
└ Completed in 2.35s
┌ [2/4] �  Fetching dependencies
│ info pruneDeps Excluding 14 dependencies. For more information use `--verbose`.
└ � Failed
HttpError: Failed to fetch dependencies:
- @matrix-org/olm@3.2.14

error Command failed with exit code 1
```

### Expected behavior

Installs fine, without error, as it does on my Mac.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: MacOS
- Browser: Chrome
- Version: 111.0.5563.149 

### Additional context

My browser console shows a request to:
```
Request URL: https://t.staticblitz.com/w/v13/h/e/@matrix-org/olm@3.2.14?o=https://stackblitz.com
Request Method: GET
Status Code: 400
```
However, when I run `npm install hydrogen-view-sdk` on my local machine (a Mac with node 18) it works fine.

**Comment by d3lm** [comment]
👋 Thanks for the report! I think the error is legit because `@matrix-org/olm` doesn't seem to exist and is not published to the npm registry, at least it's not a public package:

<img width="608" alt="image" src="https://user-images.githubusercontent.com/12571019/235657291-55f66f8d-b369-4c02-878a-9bac434b3eca.png">

You can verify by running `npm view @matrix-org/olm` on your local machine.

It does look like `hydrogen-view-sdk` [depends on it](https://www.npmjs.com/package/hydrogen-view-sdk?activeTab=dependencies) but the package [no longer exists](https://www.npmjs.com/package/@matrix-org/olm).

**Comment by SamVerschueren** [comment]
Closing this issue as it got stale. Feel free to create a new issue if you are still running into this.
