### ISSUE TITLE
"name can only contain URL-friendly characters" on package install

### ISSUE THREAD

**Issue by CyberAP** [stackblitz/webcontainer-core#113]
**Describe the bug:**
Try installing any package that contains an `@` character in it. For example: `@formatjs/intl-pluralrules/polyfill`.
The npm would fail with the following message: 

> name can only contain URL-friendly characters

**Link to the blitz that caused the error:**

https://stackblitz.com/edit/node-yqcdjc?file=package.json

**Steps to reproduce:**

1. Add `@formatjs/intl-pluralrules/polyfill` to your package.json dependencies
2. Execute `npm i` in terminal

**Expected behavior:**
A package should install as usual

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 91

**Comment by SamVerschueren** [comment]
Hi @CyberAP! Thanks for trying out StackBlitz.

The problem here is that it's actually correct that it doesn't work. If you try your example locally, you will see this error.

```
❯ npm install
npm ERR! code EINVALIDPACKAGENAME
npm ERR! Invalid package name "@formatjs/intl-pluralrules/polyfill": name can only contain URL-friendly characters

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/sam/.npm/_logs/2021-05-28T07_42_03_493Z-debug.log
```

The npm package you really want is `@formatjs/intl-pluralrules`. The `/polyfill` is just a deep import from the main package.

I forked the project here https://stackblitz.com/edit/node-reytsc?file=index.js which I guess seems to work correctly now.

StackBlitz does not support ESM right now, so `import` statements do not work. That's why I converted it to CommonJS as well.

Hopefully this helped you out 🙏 !
