### ISSUE TITLE
Port not opening with simple http server

### ISSUE THREAD

**Issue by AdrianoW** [stackblitz/webcontainer-core#114]
**Describe the bug:**
Hi all, 

maybe I am doing something wrong (I am not a pro) but it seems when running a simple NodeJS http server, the port is not opened:

![image](https://user-images.githubusercontent.com/933395/119942304-f23a4400-bf91-11eb-8171-07cce8addcaf.png)

**Link to the blitz that caused the error:**
https://stackblitz.com/edit/node-qsir7y

**Steps to reproduce:**
Create a simple server (like in the picture) and run it `node index.js`

**Expected behavior:**
The port should be opened. This is part of a bigger try on running Websockets.

**Comment by SamVerschueren** [comment]
Hi @AdrianoW! Thanks for trying out WebContainers 🙏 .

So I think the problem here is that you have another tab open with either the same project, or another project which also runs something on port `8080`. I've ran into this myself in the past and it's something we want to improve if that happens.

So a solution here is to either look for the tab that runs a project on port 8080 and close that one, or run the project on a different port.

Hope this helps and fixes your problem.

**Comment by AdrianoW** [comment]
Yeap, seems to work now. Just wondering. If I am using websockets, will the url (e.g. xxx-PORTN-xxxxx) point already to the PORT or should I use url:PORT in the end? And will Websockets work (ws://url) ?

**Comment by d3lm** [comment]
@AdrianoW Yep, `Websocket` work as usual. For the url it's enough to use `ws://localhost:1234/my-ws-route` for example. `SockJS` and `SocketIO` work as well and have been tested. If you run into issues with websockets, please let us know.

**Comment by SamVerschueren** [comment]
Let me close this issue for now. Feel free to open a new issue if you have more questions @AdrianoW or jump into our Discord 😃 .
