### ISSUE TITLE
Event Loop implementation is wrong. It runs all macrotasks before running microtask

### ISSUE THREAD

**Issue by ocodista** [stackblitz/webcontainer-core#1150]
### Describe the bug

If you run this code on Node.js

```javascript

setTimeout(() => {
  console.log('First macrotask');
  queueMicrotask(() => console.log('Add microtask from macrotask'));
  queueMicrotask(() => console.log('Add microtask from macrotask'));
  queueMicrotask(() => console.log('Add microtask from macrotask'));
}, 0);
setTimeout(() => {
  console.log('Second macrotask');
}, 0);
```

The output is
![image](https://github.com/stackblitz/webcontainer-core/assets/19851187/46825730-5508-409c-8391-1d1227a8038b)

This is because Node original Event Loop runs:
- All microtasks
- 1 Macrotask
- All microtasks

Per loop.

And this is what happens when I run the same code on stackblitz:
![image](https://github.com/stackblitz/webcontainer-core/assets/19851187/757f5ca3-9416-4fb8-b8d0-364255e289e2)

It seems your Event Loop is running
- All microtasks
- All Macrotasks
- All Microtasks

Per loop.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-4egzkj?file=index.js

### Steps to reproduce

1. Run node index.js
2. See the wrong output

### Expected behavior

Stackblitz should run 1 macrotasks, then all microtasks before running the next macrotask

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
Thanks for reporting this issue. We have a fix in PR currently and will keep you posted once it is released.

**Comment by ocodista** [comment]
Thank you @SamVerschueren.

Would love to get more insights about why is this happening if possible 😅

I'm curious!

**Comment by SamVerschueren** [comment]
I can't get into depth here unfortunately.

The problem is that the event loop in Node.js is not identical to how the browser handles this. Node.js has things like `process.nextTick`, `setImmediate`, ... All things that don't exist in the browser. So basically interacting correctly with the browsers task queue is not as flexible as Node.js.

**Comment by SamVerschueren** [comment]
This is now released and works as expected.

It took way longer than anticipated because of... reasons. We had to do a Node.js upgrade in the mean time which made things more complex and priorities got somehow shifted.

Anyways, the output is now what you see on local as well. Thanks for your patience 🙏 .

**Comment by ocodista** [comment]
Thank you, Sam!

Would you be able to explain why those things happened? (I'm curious!)
