### ISSUE TITLE
A issue with the console 

### ISSUE THREAD

**Issue by Ultron3050** [stackblitz/webcontainer-core#1174]
### Describe the bug

The console doesn't respond for anything I enter, Soo I entered "ng generate component product-details" and pressed enter but there was no response at all not even an error message but everything else works fine the console doesn't respond to anything

### Link to the blitz that caused the error

https://stackblitz.com/edit/7erjyj?file=src%2Fapp%2Fapp.module.ts

### Steps to reproduce

Type: ng generate component product-details

Then press enter

### Expected behavior

It should as in my knowledge created new component named "product-details"

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/113977400/7b06b166-2a16-4852-b11d-5a4dea4217ba)

### Platform

```
Browser name  = Chrome
Full version  = 116.0.0.0
Major version = 116
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 107095508,
  "usedJSHeapSize": 88574780,
  "jsHeapSizeLimit": 4294705152
}
Hash = 33975f1d
```

### Additional context

Fix it if possible or tell me If I'm doing something wrong

**Comment by Nemikolh** [comment]
Hey @Ultron3050! 👋

This is also something you get on local if you run `npm start` on this project and try to type any commands in the same terminal.

It is expected because stdin / stdout is now controlled by the process spawned by the shell.

To type a new command you can either:

 - Open a new terminal with the `+` button on the top right corner of the terminal 
 - Kill the running process with `Ctrl+C` (`Cmd+C` on macOS)
 
Let me know if you have any more questions!
