### ISSUE TITLE
simple algorithm try in TypeScript 

### ISSUE THREAD

**Issue by muhammadalhrake** [stackblitz/webcontainer-core#121]
**Describe the bug:**
Take a long time and does not give a result 

**Link to the blitz that caused the error:**
https://stackblitz.com/edit/typescript-akcpa6
**Steps to reproduce:**

1. Go to 'https://stackblitz.com/edit/typescript-akcpa6'
2. Click on 'setInterval(()=>console.log(generateQuestion(5,5,"=10")),500);'
3. Click on  'Alt+shift+A'

**Expected behavior:**

just fix the error in settings , 
**Screenshots:**

![image](https://user-images.githubusercontent.com/58793543/120062142-42380a00-c069-11eb-8015-731d26fa9959.png)

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] .. 
    Chrome browser 
**Smartphone (please complete the following information):**
    
**Additional context:**

**Comment by KwintenP** [comment]
Hi, 

It seems to work on my end. Could it be that the Chrome instance you were running Stackblitz in crashed? Specially since your screenshot also shows a different tab being frozen.

As an FYI, this seems to be an issue with a V1 project (not using WebContainers). If the error persists, please open an issue on https://github.com/stackblitz/core for this.
