### ISSUE TITLE
Why do I need crossOriginIsolated to be true if I have SharedArrayBuffer via an origin trial?

### ISSUE THREAD

**Issue by DustinBrett** [stackblitz/webcontainer-core#1245]
### Describe the bug

I desire to use WebContainers in my app for Chrome users. I have signed up for [Trial for SharedArrayBuffers in non-isolated pages on Desktop platforms](https://developer.chrome.com/origintrials/#/view_trial/303992974847508481) which is an origin trial that allows `SharedArrayBuffers` to exist without the page being cross-origin isolated.

My question/request is, can we avoid checks for `crossOriginIsolated == true` if what matters is the existence of the `SharedArrayBuffer` function?

I have no link because this is domain specific and not hosted as it doesn't work.

### Link to the blitz that caused the error

N/A

### Steps to reproduce

1. Add the origin trial to your website
2. See SharedArrayBuffer exists
3. Try and load WebContainers and be told you need crossOriginIsolated for SharedArrayBuffer to work

### Expected behavior

That it allows SharedArrayBuffer existing to be enough to continue, regardless of the state of crossOriginIsolated.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: All Platforms
- Browser: Chrome
- Version: 92+

**Comment by SamVerschueren** [comment]
Is there a specific reason why you don't want to add the [2 headers](https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/#enabling-cross-origin-isolation) to make your website/app cross-origin isolated?

**Comment by DustinBrett** [comment]
> Is there a specific reason why you don't want to add the [2 headers](https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/#enabling-cross-origin-isolation) to make your website/app cross-origin isolated?

Yes I have several apps on my site which use iframes to function. If I added those headers then these other apps would cease to function.

There are anonymous iframes (https://developer.chrome.com/blog/anonymous-iframe-origin-trial/#challenges-with-enabling-coep), but this is also not support outside Chrome.

Is there a reason that StackBlitz checks for crossOriginIsolated beyond the idea that it's required for SharedArrayBuffers?

**Comment by Nemikolh** [comment]
Hey @DustinBrett !

> Is there a reason that WebContainers checks for `crossOriginIsolated` beyond the idea that it's required for `SharedArrayBuffer`s?

I'm not entirely sure, we might be able to simplify the check.

In the meantime, let's see what are your other options.

In your initial post you said:

> I desire to use WebContainers in my app for Chrome users.

And in your latest comment you talk about usage outside of Chrome:

> There are anonymous/credentialless iframes but this is also not supported outside Chrome.

So I presume that you would use WebContainers only for Chrome users and not use WebContainer for other users but you would still want your iframes to work, correct?

If yes, before serving the COEP/COOP headers you could detect whether or not the browser is chrome and based on that serve the content with those headers or not. You would also use your anonymous iframes only if it's chrome.

Now with this approach, regardless of the origin trials expiring, you could use WebContainers _now_.

**Comment by DustinBrett** [comment]
> Hey @DustinBrett !
> 
> > Is there a reason that WebContainers checks for `crossOriginIsolated` beyond the idea that it's required for `SharedArrayBuffer`s?
> 
> I'm not entirely sure, we might be able to simplify the check.
> 
> In the meantime, let's see what are your other options.
> 
> In your initial post you said:
> 
> > I desire to use WebContainers in my app for Chrome users.
> 
> And in your latest comment you talk about usage outside of Chrome:
> 
> > There are anonymous/credentialless iframes but this is also not supported outside Chrome.
> 
> So I presume that you would use WebContainers only for Chrome users and not use WebContainer for other users but you would still want your iframes to work, correct?
> 
> If yes, before serving the COEP/COOP headers you could detect whether or not the browser is chrome and based on that serve the content with those headers or not. You would also use your anonymous iframes only if it's chrome.
> 
> Now with this approach, regardless of the origin trials expiring, you could use WebContainers _now_.

Hi @Nemikolh,

Thanks for the response. One issue I have with dynamically adding headers is that my app is entirely client side and runs directly via nginix/CloudFlare CDN. I likely could add something in between via CloudFlare Workers or something, but the use of WebContainers will not be a primary use case within my site so I don't desire any overhead before the user decides they want WebContainers.

I was excited about the SharedArrayBuffer origin trial, thinking this could at least get me until March 7, 2024 (end of origin trial - unless extended), at which point ideally I would like to support Firefox/Safari also if they've gone onboard with credentialless in some way.

If no other alternative can be found then indeed I can consider dynamic headers, but I also may wait if that is the case.

I appreciate you considering my question either way.

**Comment by Nemikolh** [comment]
Ah I see, makes lots of sense :+1: 

I'll add a ticket to our internal issue tracker so we can investigate this in a bit more details. It's possible that our check is a bit too restrictive.

**Comment by Nemikolh** [comment]
Hey @DustinBrett!

I was curious if you had tried providing `coep: 'none'` to [`WebContainer.boot`](https://webcontainers.io/api#boot-options)?

This should serve the iframe without the COEP/COOP headers and might unblock you. If it does not, then what error do you get?

**Comment by DustinBrett** [comment]
> Hey @DustinBrett!
> 
> I was curious if you had tried providing `coep: 'none'` to [`WebContainer.boot`](https://webcontainers.io/api#boot-options)?
> 
> This should serve the iframe without the COEP/COOP headers and might unblock you. If it does not, then what error do you get?

That looks like exactly what I need. I guess I missed this last time I tried it. Thanks for mentioning it! I will try it and comment with any updates.

**Comment by DustinBrett** [comment]
> Any update @DustinBrett? Is `coep: 'none'` what you were looking for and is it working for you?

Sorry I haven't had time to recreate this but likely it would help as the docs describe what I wanted. As soon as I have time I can update this or if there is a desire to close it then it could be closed as a possible solution and I can reopen it if it doesn't work out.

**Comment by goleary** [comment]
I'm trying to use WebContainers on our client-side app that is served with this header:
```
  "Cross-Origin-Embedder-Policy": "credentialless",
```
I removed the COOP header because it breaks our google login via OAuth.

I thought that opting into the origin trial and supplying that header/meta tag to enable the SharedArrayBuffer would do the trick, but even with `SharedArrayBuffer` accessible on our domain (confirmed via devtools) the WebContainer does not work.

Before finding this thread, I tried with just the Origin-Trial token and using `WebContainer.boot()`, but still got this error:
```
Failed to execute 'postMessage' on 'Worker': SharedArrayBuffer transfer requires self.crossOriginIsolated.
```
After finding this thread, I updated to use `WebContainer.boot({ coep: "none" });`. Now I get no error, but the WebContainer doesn't actually appear to boot (execution hangs).

I guess we're going to have to move our OAuth flow to a different app served via a separate route (different headers) if we want to use WebContainers?

Any suggestions on what else to try?

**Comment by goleary** [comment]
Found [this issue](https://github.com/stackblitz/webcontainer-core/issues/1094) which led me to understand that I needed to remove both COOP & COEP headers in order for `WebContainer.boot({ coep: "none" });` to work correctly.

So now we use the headers when developing locally (don't care about OAuth here), but with our production deployed app we use the origin-trial + `coep: "none"`.


I will say that this behavior is not well documented, and it took sifting through closed GitHub issues to arrive here.

A few things could help:

- Document [here](https://webcontainers.io/api#coep-require-corp-credentialless-none) that the COOP & COEP headers must be entirely remove for `coep: 'none'` to work correctly.
- Have a reasonable error spit out of the WebContainer when it is booted with an invalid config (instead of hanging indefinitely).
- I was working off [this document](https://blog.stackblitz.com/posts/cross-browser-with-coop-coep/), which vaguely mentions the origin trial, but without mentioning how it should be implemented. A link to [this](https://webcontainers.io/api#coep-require-corp-credentialless-none) part of the docs would have been super useful (especially if the above update is made)
