### ISSUE TITLE
BUG: argon2 cannot be used

### ISSUE THREAD

**Issue by zaiste** [stackblitz/webcontainer-core#125]
**Describe the bug:**

I cannot use the [`argon2`](https://github.com/ranisalt/node-argon2) package inside the web container.

**Link to the blitz that caused the error**

https://stackblitz.com/edit/argon2?file=index.js

**Steps to reproduce:**

1. Go to 'https://stackblitz.com/edit/argon2?file=index.js'
2. In Terminal, write `node index.js`
3. See error

```
Error: Cannot find module '/projects/argon2/node_modules/argon2/lib/binding/napi-v3/argon2.node'
Require stack:
- /projects/argon2/node_modules/argon2/argon2.js
- /projects/argon2/index.js
```

**Expected behavior:**

No error.

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 92.0.4515.20
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.20 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 91227648,
  "usedJSHeapSize": 83238304,
  "jsHeapSizeLimit": 4294705152
}

**Additional context:**

**Comment by KwintenP** [comment]
It looks like this package is using the n-api and thus native packages. Since everything in running inside the browser, it's not possible to use native packages. 
Unfortunately, this will never work in WebContainers. To make this work, the `argon2` should switch to a WASM based implementation that allow it to run in the browser.
