### ISSUE TITLE
Nuxt devtools fails to load.

### ISSUE THREAD

**Issue by NBT22** [stackblitz/webcontainer-core#1269]
### Describe the bug

The embedded devtools for nuxt fail to load. It first requires you to connect to the project, then says something went wrong.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nuxt-starter-ubmul4

### Steps to reproduce

1. Start the project
2. Open port 3000
3. Open the devtools
4. Attempt to connect to project

### Expected behavior

The devtools should load properly.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![image](https://github.com/stackblitz/webcontainer-core/assets/91098724/26ff102a-e82a-4aea-a59c-eb8af3f111ba)

### Platform

- OS: ChromeOS
- Browser: Chrome
- Version: 121.0.6126.0

**Comment by NBT22** [comment]
I ended up having two updates to install, so after getting those installed I can say that the issue persists on version 121.0.6154.0, and I was unable to have the issue on 121.0.6167.9 due to #1260

**Comment by kirjavascript** [comment]
Hi 👋 thanks for reporting this issue!

We are tracking it internally after replicating it and will post here when we have any updates

**Comment by sqcheah** [comment]
Hi @kirjavascript ,
I think this is due to nuxt/devtools@7ec0d3c84e817be849e0249e2bb5cee0f7336953 

Reproduction:
Devtools v1.0.4 (before change)
https://stackblitz.com/edit/nuxt-starter-fvj2hn?file=app.vue

Devtools v1.0.5 (after change)
https://stackblitz.com/edit/nuxt-starter-bicvgm?file=app.vue
I provide a solution where it revert back the changes and it works fine

The changes are my suggestion originally from nuxt/learn.nuxt.com#68
The issue i am fixing is when we set the COOP/COEP headers for the webcontainers, the devtools url does not inherit those headers because it's injected by nuxt modules, so i try to bypass it by modifying the iframe attributes.

**Comment by NBT22** [comment]
When I tested this I discovered that (in chrome) v1.0.5 does not work and v1.0.4 does. In firefox they both work. I may have been misreading your comment, but this is the opposite of what I thought you were saying should be happening?

**Comment by sqcheah** [comment]
@NBT22 , yes v1.0.4 works and v1.0.5 doesn't. I may have not been clear, but the solution i mentioned was inside the v1.0.5 stackblitz, if u uncomment those lines, then it works. The solution is to revert back what the commit does.
<img width="648" alt="Screenshot 2023-12-19 at 10 10 15" src="https://github.com/stackblitz/webcontainer-core/assets/52320846/f49d80bc-8d1b-4ff8-a7d0-334ac014c91c">

**Comment by NBT22** [comment]
Oh I understand now, thank you!

**Comment by d3lm** [comment]
Is this one resolved or what is the status here?

**Comment by sqcheah** [comment]
Its resolved. The devtools on the latest stackblitz playground works fine. See nuxt/devtools@0eb7a82bef1639ebfeace68f73ccebc11ea8e0a6
