### ISSUE TITLE
Can't run project created from Stackblitz's TS template

### ISSUE THREAD

**Issue by alex1yaremchuk** [stackblitz/webcontainer-core#1296]
### Describe the bug

Preview panel hangs in "Booting WebContainer". 

Link to problemmatic repository (for example): 
https://stackblitz.com/~/github.com/alex1yaremchuk/typescript-psui7n

I opened Getting started with WebContainer project and preview works ok there for me. 

Probably TS template misses some essential settings for WebContainer to work? 

![image](https://github.com/stackblitz/webcontainer-core/assets/40666786/0c7d1fb2-f3e4-431a-a653-d0862943c3ee)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/alex1yaremchuk/typescript-psui7n

### Steps to reproduce

1) add new Stackblitz project by Typescript template
2) click Create a Repository button
3) repository is created, ide in the browser starts but preview doesn't work. 

### Expected behavior

Preview window should work for a blank TS project

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by SamVerschueren** [comment]
Hey @alex1yaremchuk 👋 . The problem here is that the original project (where it worked) has some more magic under the hood to make it work out of the box. While WebContainer is just like running Node.js locally. If you download this project locally, it doesn't work out of the box either. So WebContainer gives you more power as it's more flexible, but it doesn't automatically run things for you, unless configured through `package.json`.

I believe there are plans on a migration path from older projects to WebContainer projects. Which would mean that depenendencies and scripts are automatically configured for you. Let me see if I can find some information for you.
