### ISSUE TITLE
How to use without NPM and vite

### ISSUE THREAD

**Issue by godalming123** [stackblitz/webcontainer-core#1297]
**Is your feature request related to a problem? Please describe:**
I want to be able to use web containers without NPM by just copying and pasting a few files, and then adding a script tag to my HTML.

**Describe the solution you'd like:**
I think that their should be docs on how to achieve this, the solution shouldn't need to make network requests to external locations.

**Comment by godalming123** [comment]
Hi, currently I'm using the live-server NPM package because it adds a small script to automatically reload the page on file changes, and I definitely don't want another static server implementation inside this project. I mainly want this for simplicity  as it allows me to not have a node_modules folder if I install live-server globally, and it is much more portable (EG: I can just copy the code into hostinger to deploy.)

**Comment by SamVerschueren** [comment]
I created a small example with only an `index.html` and a `script.js` file. https://stackblitz.com/~/github.com/SamVerschueren/static-html

I used a `.stackblitzrc` to add a automated start command that spawns `lite-server` (identical to `live-server` but `live-server` was not auto-reloading for me 🤷 ).

Hope this helps!

**Comment by SamVerschueren** [comment]
Instead of npm, you can spawn whatever command you want. You could do `npx -y live-server` as well. I created a small example for you https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-bha5op?file=main.js. As you can see, it doesn't use `npm install` first as it directly uses `live-server` to serve the files from `files.js`. But instead of running `npx`, you could also create a `server.js` entry (in `files.js`) and run `await webcontainerInstance.spawn('node', ['server.js']);` which then spawns your own web server.

Hopefully this answers your question?

**Comment by fvsch** [comment]
If you want a small npm package (that you could even vendor in, instead of loading from npm's registry), it looks like `servor` is a great tiny option:
https://twitter.com/sulco/status/1747720306767048937

**Comment by SamVerschueren** [comment]
Thanks for the tip @fvsch! I've switched my tiny example to use `servor` now 🔥 .
