### ISSUE TITLE
Specified extension not appearing in the recommendations window

### ISSUE THREAD

**Issue by Lootjs** [stackblitz/webcontainer-core#1299]
### Describe the bug

In the Visual Studio Code project, the specified extension Lootjs.Drevolootion listed in .vscode/recommendations.json is not appearing in the recommendations pop-up window. Instead, other extensions like wix.vscode-import-cost are being recommended, even though Lootjs.Drevolootion is explicitly listed in the project's recommendation settings.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/Lootjs/demo_vscode_i18n-quickview

### Steps to reproduce

1. Open the .vscode/recommendations.json file in the project.
2. Add the extension ID Lootjs.Drevolootion to the array in the recommendations.json file.
3. Open the project in Visual Studio Code.
4. Observe the extensions recommended in the pop-up window.

### Expected behavior

The extension Lootjs.Drevolootion should be prominently displayed in the recommendations pop-up when the project is opened in Visual Studio Code, as it is specified in the .vscode/recommendations.json file, alongside any other listed extensions.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.84.0
Hash = 0c70e92b3d3a027d78ae676e788f37bcd21bac24
WebContainer = babcaeac

Browser name  = Chrome
Full version  = 120.0.0.0
Major version = 120
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87362266,
  "usedJSHeapSize": 81933230,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hey @Lootjs 👋 . Thanks for reaching out.

The reason `Lootjs.Drevolootion` is not shown in the recommended extensions, is because we can't use the VSCode marketplace. We're legally not allowed to use them. For that reason, we use an open alternative called [Open VSX Registry](https://open-vsx.org/).

If you want `Lootjs.Drevolootion` to appear, you will have to publish your extension to Open VSX as well. After that it should start appearing (depending on the caching of Open VSX).

Hope this information helps. Let us know if there's anything else we can help you with.
