### ISSUE TITLE
is there a way to set cache size in ios, the page reloads before its done

### ISSUE THREAD

**Issue by dayvedallen** [stackblitz/webcontainer-core#1302]
**Is your feature request related to a problem? Please describe:**

**Describe the solution you'd like:**

**Describe alternatives you've considered:**

**Additional context:**

**Comment by SamVerschueren** [comment]
Hey @dayvedallen 👋 . Thanks for reaching out.

Please do fill in all details before creating the issue. That always helps us to more quickly identify what the possible problem could be.

From what I understand from the issue title is that iOS auto-refreshes when running a project. The problem is that iOS is very very restrictive in the amounts of memory a webpage can use. If the amount of memory exceeds a certain threshold, it will refresh to clean up the memory. There's currently no way to increase that.
