### ISSUE TITLE
No more Angular menu for generating services, components

### ISSUE THREAD

**Issue by AlexDmr** [stackblitz/webcontainer-core#1335]
### Describe the bug

There is no more contextual menu on the file explorer that display Angular schematics on Angular project

### Link to the blitz that caused the error

https://stackblitz.com/edit/l3m-cc-machine-2023-2024?description=An%20angular-cli%20project%20based%20on%20@angular/animations,%20@angular/common,%20@angular/compiler,%20@angular/core,%20@angular/forms,%20@angular/platform-browser,%20@angular/platform-browser-dynamic,%20@angular/router,%20core-js,%20rxjs,%20tslib%20and%20zone.js&file=package.json&template=node&title=Angular%20Starter

### Steps to reproduce

1.  Create a new Angular project
2. Try to add a new componenent from the file menu

### Expected behavior

The menu should propose to deal with Angular schematics (componenets, services, pipe, ...) but it only proposes to create file and directory.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 121.0.0.0
Major version = 121
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Safari/537.36 Edg/121.0.0.0
performance.memory = {
  "totalJSHeapSize": 64116517,
  "usedJSHeapSize": 59888249,
  "jsHeapSizeLimit": 4294705152
}
Hash = a9c8a5a3
```

**Comment by sulco** [comment]
Hey @AlexDmr 👋 . Thanks for reaching out.

That's correct, we have removed that from our official Angular starter projects in the recent update (you can read about this in "[Starters Upgrade: WebContainers and Vite](https://blog.stackblitz.com/posts/webcontainers-starters-update/)" blog post). 

These generators were our custom implementation of a subset of the Angular generators. Although they worked, they weren't actively maintained, and the difference between their behavior and what you'd get when running the actual generator was increasing.

On the positive note, since the new starters are based on WebContainers, they have a terminal. This means we can use the `﻿ng generate` command, which relies on Angular CLI and can run the full range of generators, including custom schematics.
