### ISSUE TITLE
BUG: Live result window is not working

### ISSUE THREAD

**Issue by abhishekdam** [stackblitz/webcontainer-core#136]
**Describe the bug:**
The live out put window is not booting at all i am clicking on the open in new window but nothing is happening.

**Link to the blitz that caused the error**
https://stackblitz.com/edit/node-ao9mjd

**Steps to reproduce:**

1. Go to 'create a new repo nodejs'
2. Click on 'click on open in new window'
3. nothing is happening

**Expected behavior:**
should have open a new out put window

**Version of webcontainer:**
Hash: 57be275669708b1d42e233d60c80159bef577631

**Screenshots:**
![Screenshot from 2021-06-01 16-59-18](https://user-images.githubusercontent.com/33367709/120316226-d10f8580-c2fa-11eb-8d71-db4530cce3e7.png)

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 91.0.4472.77
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 51704097,
  "usedJSHeapSize": 48593769,
  "jsHeapSizeLimit": 2038956032
}

**Additional context:**

**Comment by SamVerschueren** [comment]
It's definitely a bug. The thing here is that no HTTP server is running, so the preview window doesn't actually show you a webpage. When you click the `Open in a new window` button, it opens the webpage from the preview window in a separate browser window.

For instance, try creating a `http-server` by forking that project https://stackblitz.com/fork/http-server. Wait for the the server to start and then press the `Open in a new window`. You'll see that it will just work, but it will also close the preview window automatically. Because that's mostly what you want.

In your case, because you don't have a URL, we can't open it, but it still closes the preview window. It would be better from our side if we showed a message indicating that it couldn't open the preview because there is none.

**Comment by abhishekdam** [comment]
yup its working thanks man really thankyou
