### ISSUE TITLE
Cannot use "cd projectname"

### ISSUE THREAD

**Issue by Nazeofel** [stackblitz/webcontainer-core#1458]
### Describe the bug

Hello, I am trying to setup a webContainer but when creating my project with npx I cannot CD into it

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-srlthz?file=src%2Fhooks%2FuseContainer.ts,src%2FApp.css,src%2FApp.tsx&terminal=dev

### Steps to reproduce

Open the stackblitz

Open dev tools

Check the logs

see that even after the cd command in src/hooks/useWebContainer the ls -a command does not print the inside the of "myproject" folder.

### Expected behavior

going into my project folder and seeing the content inside.

<img width="734" alt="image" src="https://github.com/stackblitz/webcontainer-core/assets/96749659/7f376a05-405b-4a85-aa4e-f6794e012d9d">

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

Browser Chrome for the stackblitz

Mac when using it locally

**Comment by SamVerschueren** [comment]
Hey @Nazeofel 👋 ! Thanks for reaching out!

So the thing is that you should see `webcontainer.spawn()` the same way as Node.js `child_process.spawn()`. Running `cd folder` doesn't do anything for the next spawned process as it will just start fresh with the current working directory.

The problem here was that you couldn't specify the working directory of the child process, which is what I now added (because of this issue). You can read more about this property on the [API reference on webcontainers.io](https://webcontainers.io/api#%E2%96%B8-cwd-string).

For this to work, you will need to use `@webcontainer/api@1.2.0` though. You can then change the `ls -a` spawned process to

```ts
const ls = await webContainer.spawn('ls', ['-a'], {
  cwd: 'myproject'
});
```

And the one you use to run the dev server

```ts
await webContainer.spawn('npm', ['run', 'dev'], {
   cwd: 'myproject'
});
```

I forked your project and made some small changes https://stackblitz.com/~/edit/vitejs-vite-ypethu?file=src/hooks/useContainer.ts. It's complaining about an API key that is missing though, so that's why it's not starting up.

> error - DISCORD_TOKEN or DISCORD_CLIENT_ID not found in environment variables

Hope this helps 🙏 .

**Comment by SamVerschueren** [comment]
I'm closing this issue for now as I think it is resolved. Let me know if there's anything else you run into.
