### ISSUE TITLE
The express application listen fails 

### ISSUE THREAD

**Issue by gokuney** [stackblitz/webcontainer-core#220]
**Describe the bug:**
Port assigned to express application works only single time. when application is run again the container says that no server is listening on the port

**Link to the blitz that caused the error**
https://stackblitz.com/edit/google-drive-connector?file=index.js

**Steps to reproduce:**

1. Go to index.js
2. Check app.listen(PORT)
4. Run command in shell: `node index.js`
5. No errors, server starts listening 
6. Nothing on output. No server listening on port

**Expected behavior:**
Code should be running on the defined port

**Version of webcontainer:**
Hash: 70a1ff62a0f0131ac0df3c30faf487fef744ac90

**Desktop (please complete the following information):**
```
Browser name  = Chrome 
Full version  = 91.0.4472.106
Major version = 91
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 85320413,
  "usedJSHeapSize": 79289465,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by nishantSg** [comment]
The same thing happened to me while using the node http server. It's not just one time, sometimes it will listen on the same port after restarting but once it starts failing you have to refresh the page to reboot the web container.

**Comment by gokuney** [comment]
Thanks, this seems to have resolved my issue for now.  A bit inconvenient but will do for now.

**Comment by d3lm** [comment]
Hm I think this is actually a bug, so I am reopening this issue because I am sure I ran into the same a few times. It seems that when the process is killed that the server is not properly killed and restarting it will fail then cause it checks if the port is taken or not. And if it's taken it won't spin up the server. This needs a bit more investigation from our side. Thanks for reporting this issue!

**Comment by jrvidal** [comment]
@gokuney We're having trouble reproducing this bug now, a related fix might have solved the issue. Are you still able to reproduce it?

cc @nishantSg

**Comment by nishantSg** [comment]
Sorry, I had not used stackblitz for quite a while. I tried to run a few old projects and now I am not getting that problem. It might have been fixed. I will update here in future if It comes up.

**Comment by gokuney** [comment]
Hey @jrvidal ,
I no longer get the error now. You're right, some related fix might have solved this. :smiley: 
Let me close this bug for now. Thanks

**Comment by n3ko** [comment]
Seems to me, this issue is present again (or still)
1) I open url [https://stackblitz.com/edit/google-drive-connector?file=index.js](https://stackblitz.com/edit/google-drive-connector?file=index.js) (firefox dev. edition 109.0b3, or googe chrome 108)
2) in the vscode terminal type `node index.js` the in-editor-browser opens, its fine, BUT
3) click on 🔌 on the left (ports in use) and ... in chrome works (most of the time at least) and in ff like never.

i really not understand, how the magic works behind this stuff, but i _strongly feel_ its related with the tracking protection.

Sry if its not appropriate, to comment on a closed issue, i just thought it might useful if written down
