### ISSUE TITLE
Tailwind Dark Mode doesn't work side-by-side

### ISSUE THREAD

**Issue by deadcoder0904** [stackblitz/webcontainer-core#271]
### Describe the bug

Tailwind Dark Mode doesn't show in Preview. It only shows when **Open a New Window** is clicked

### Link to the blitz that caused the error

https://stackblitz.com/edit/github-6frqvs-qvxcvt

### Steps to reproduce

Just open the Stackblitz & see. Click on the toggle which u probably can't see so highlight the text.

### Expected behavior

Dark Mode should be visible

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.107
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78894922,
  "usedJSHeapSize": 72427146,
  "jsHeapSizeLimit": 4294705152
}
Hash = 548843700a830a9170c7b4f676310f668ec52ffc
```

**Comment by EricSimons** [comment]
Thanks for the report @deadcoder0904! Seems like there's something wonky going on with it being in an iframe where the body background isn't changing color properly 🤔  Will investigate with the team!

**Comment by fvsch** [comment]
Thought like I had replied here before, but apparently not!

The issue is that browsers:

1. Keep the iframe's background transparent;
2. May change the iframe document's _text_ color to white or black or something else depending on
    - the OS color scheme,
    - the browser's theme,
    - the iframe document's `<meta name="color-scheme" value="dark|light">`,
    - or the iframe document's `:root { color-scheme: dark|light }` CSS property;
3. DO NOT set the iframe document's `background-color` when setting its text `color`.

On our side, our editor UI uses a dark theme by default. Most users still have a light mode OS setting, so by default text in the preview iframe will be black. To avoid showing black text on top of the dark background of our editor UI, which would be unreadable, we set a white background behind the iframe. This works well for the majority use case.

In the minority use case where users use a dark mode OS, or a dark theme for their browser (and the browser uses that as a signal for the default text color of documents), then the browser may set the iframe's text to white or some other light color, and then you'll end up with white text in a transparent iframe on top of a white background, which obviously is not great.

The problem doesn't happen when opening the preview in a new tab, because the browser will set the tab's background color (not the _document_'s background color) to something dark, so you have light text on a dark background and that's readable. It's a problem that mostly affects iframes.

We might want to try to work around this by using [prefers-color-scheme](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) in the parent document, but I don't think we have a guarantee that matching `(prefers-color-scheme: dark)` in the parent document means that it would match in the iframe document, and it doesn't guarantee that the iframe document doesn't explicitly sets `:root { color-scheme: light }` and ends up with dark text, so using this signal to replace our white backdrop with a dark one could break as many projects as it fixes. Sounds like a game of whack-a-mole.

IMO the solution is for authors of web pages to make sure that they do not rely on browser defaults that may fail to provide correct contrast, and instead explicitly set text and background colors for their pages, e.g. for a light theme:

```css
:root {
  color-scheme: light;
  color: black /* or some dark color */;
  background-color: white /* or some light color */;
}
```

and for a dark theme:

```css
:root {
  color-scheme: dark;
  color: white /* or some light color */;
  background-color: white /* or some dark color */;
}
```

**Comment by fvsch** [comment]
After revisiting this issue, we identified specific combinations of parameters where showing a transparent iframe on top of a white backdrop would result in unreadable text:
https://docs.google.com/spreadsheets/d/1R9knWZN7KB-y_3JAov4LDYWfHIzenGCtMJrQikttTBs/edit

For now we've decided to fix this issue by removing the `color-scheme` declaration in the parent document (https://stackblitz.com/edit/<project-id>), which gives better results in Google Chrome. In our tests, there are differences in how browsers treat `color-scheme`, so for best results we still recommend that pages should:

1. Declare a correct `color-scheme` value on the root element.
2. And also declare a matching `color` and `background-color` pair of colors on the root element.
