### ISSUE TITLE
Failed to fetch jointjs

### ISSUE THREAD

**Issue by tony19** [stackblitz/webcontainer-core#301]
### Describe the bug

Trying to install `jointjs` from npm results in an `HttpError`:

❯ npm install
warn preInstall No description field
warn preInstall No repository field
warn preInstall No license field
┌ [1/3] 🔍  Resolving dependencies
└ Completed in 0.651s
┌ [2/3] 🚚  Fetching dependencies
└ 𐄂 Failed
HttpError: Failed to fetch dependencies:
- jointjs@3.4.0

error Command failed with exit code 1

### Link to the blitz that caused the error

https://stackblitz.com/edit/stackblitz-failed-to-fetch-jointjs?file=package.json

### Steps to reproduce

1. Go to sandbox, which runs `npm install` (or do it manually from the terminal with `npm i jointjs`)
2. Observe the error.

### Expected behavior

`jointjs` is installed as a dependency

### Platform

```
Browser name  = Chrome 
Full version  = 92.0.4515.131
Major version = 92
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 78187450,
  "usedJSHeapSize": 65666614,
  "jsHeapSizeLimit": 4294705152
}
Hash = f91df8ee833f18bedf806af681eeaccd3addac72
```

**Comment by jrvidal** [comment]
@tony19 Thanks for reporting, we'll be looking into this.

**Comment by jrvidal** [comment]
@tony19 The problem here is that `jointjs` is just too big. We do have size limits for the packages we download during installation, lazy-loading the rest when needed. However our heuristics do not cover `jointjs` yet.

We do want to fix this issue, and it's in our internal roadmap. However, I've filed https://github.com/clientIO/joint/issues/1525 upstream, because the size of this package does not seem reasonable to me.

**Comment by jrvidal** [comment]
@tony19 turbo does handle this graciously now :tada: Thanks for the report!
