### ISSUE TITLE
BUG: pnpm doesn't install on WebContainer

### ISSUE THREAD

**Issue by okikio** [stackblitz/webcontainer-core#396]
### Describe the bug

I get this error while trying to install `pnpm`

![image](https://user-images.githubusercontent.com/17222836/141356586-bf8992e4-4b6b-46a2-83ac-0efed5609132.png)

### Link to the blitz that caused the error

https://stackblitz.com/github/okikio/native/tree/beta

### Steps to reproduce

1. Go to [the linked blitz](https://stackblitz.com/github/okikio/native/tree/beta)
2. Run `npm i pnpm` in the terminal
3. Error.... 
![image](https://user-images.githubusercontent.com/17222836/141356776-a9fcdeff-263a-4c7c-97cc-5ef03a090b5c.png)

### Expected behavior

The expected behaviour is that `pnpm` gets installed and that I can use `pnpm` as an alternative package manager to `npm`. 

### Screenshots

![image](https://user-images.githubusercontent.com/17222836/141356796-b4dfbb6c-71af-4690-979f-ba347eefa92b.png)

### Platform

- OS: Windows
- Browser: Edge
- Version: 96.0.1054.13 (Official build) beta (64-bit)

**Comment by geromegrignon** [comment]
By opening your Stackblitz project, there is already an error in the console while resolving dependencies:

![image](https://user-images.githubusercontent.com/32737308/141357677-d3d82900-7bb3-409c-b99e-ba982bf5003e.png)

I encourage you to try to fix it first before caring about pnpm.
About pnpm I just tried on a new Stackblitz project and it works as expected.

**Comment by okikio** [comment]
@geromegrignon I'm not sure what is causing StackBlitz to crash, the error it gives is vague

**Comment by geromegrignon** [comment]
Does your project run locally?

**Comment by okikio** [comment]
Yeah

**Comment by jrvidal** [comment]
@okikio The error is due to `workspace:*` URLs in your `package.json`. Our NPM client, [turbo](https://developer.stackblitz.com/docs/platform/turbo/), is modeled after `npm`/`yarn` and we don't support those (which I assume are a pnpm-specific feature?).

Now, pnpm _might_ work if you install it a different folder (`mkdir foobar && cd foobar && npm init && npm add pnpm`) and call that binary directly (`./foobar/node_modules/.bin/pnpm`). I did check this and it doesn't work, we'll take a look.

**Comment by jrvidal** [comment]
@okikio The workaround above now works, to the extent that `pnpm` can retrieve the packages and write them to disk. I did notice that installation fails due to post-install scripts. There will probably more things that won't work, even in a simpler setting but, for the time being, I'm going to close this.

Please do report any other issues you find!
