### ISSUE TITLE
Editor Save Problem

### ISSUE THREAD

**Issue by paul-coder-22** [stackblitz/webcontainer-core#426]
### Describe the bug

While I'm made some changes after saving the editor the behavior of the unsaved tab remains the same.

### Link to the blitz that caused the error

https://stackblitz.com/run?file=src/app/chips-autocomplete-example.ts

### Steps to reproduce

-- Go the editor do some change and try to save it ``` ctrl + s ``` but the not save  behavior remain the same.   

### Expected behavior

As the editor similar to vscode , I want the same behavior as well.

### Screenshots

<img width="960" alt="Screenshot 2021-11-24 145506" src="https://user-images.githubusercontent.com/78898391/143210955-9e036081-3196-411e-a091-021cc68b6968.png">
-- after made some chang
<img width="960" alt="Screenshot 2021-11-24 145722" src="https://user-images.githubusercontent.com/78898391/143211320-7edc28d8-1d6f-4318-b4a2-e997a5537206.png">
e

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.45
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.45 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 119693193,
  "usedJSHeapSize": 114466861,
  "jsHeapSizeLimit": 2172649472
}
Hash = 19c34b6682252415afe6a0280c63a7c091453a84
```

### Additional context

I don't know that is a specific issue that is happening with me or not, but I'm facing it when the updated version came out of stackbliz.

**Comment by Nemikolh** [comment]
Hi @paul-coder-22 ! :wave: 

I couldn't reproduce the issue that you've encountered. I think that it has been fixed though. If that's not the case for you please reopen and if you could also share the link you click first before being redirected to `/run` that would be perfect! :pray: 

What I think might have happened is that when you tried to save the file, it's supposed to fork the blitz but for you it didn't. We've recently been working on a very similar issue which has now been fixed. If your issue was the same, then that mean it's also fixed for you. :sparkles:
