### ISSUE TITLE
Sanity.io not working

### ISSUE THREAD

**Issue by TomSmedley** [stackblitz/webcontainer-core#451]
### Describe the bug

`Error: socket hang up`

Sanity will not install.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-bs339a

### Steps to reproduce

1. Click on link above
2. Do `npm install @sanity/cli && npx sanity init`

### Expected behavior

Should install Sanity.

**Comment by jrvidal** [comment]
@TomSmedley Thanks for the report. Unfortunately, there's not much we can do at the moment, since this is fundamentally limited by CORS:

`Access to fetch at 'https://api.sanity.io/v1/auth/providers' from origin 'https://node-bs339a.w.staticblitz.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`
