### ISSUE TITLE
unsupport npm scripts with "pre" and "post"

### ISSUE THREAD

**Issue by asakurayohj** [stackblitz/webcontainer-core#481]
### Describe the bug

unsupport npm scripts with "pre" and "post" hooks

### Link to the blitz that caused the error

https://stackblitz.com/edit/webpack-study?file=package.json

### Steps to reproduce

npm run build

### Expected behavior

"postbuild" auto run after "build" script finished

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 132181669,
  "usedJSHeapSize": 127564621,
  "jsHeapSizeLimit": 4294705152
}
Hash = c1a2f33ebdb80ec1573b6337c828d176e80f0398
```

**Comment by HeyGarrison** [comment]
@asakurayohj this is expected behavior as running `postinstall` automatically has some security issues. However, you could create a `.stackblitzrc` to automatically run `npm run postinstall`. 

See docs here: https://developer.stackblitz.com/docs/platform/project-config/

Closing for now, but feel free to comment with any questions ❤️
