### ISSUE TITLE
Unable to install cypress

### ISSUE THREAD

**Issue by IanVS** [stackblitz/webcontainer-core#489]
### Describe the bug

I was attempting to create a [cypress](https://www.cypress.io/) issue reproduction, so I started a new node.js project, installed cypress, and ran `cypress install`, but I got an error:
```
❯ cypress install
Installing Cypress (version: 9.1.1)


The Cypress App could not be downloaded.

Does your workplace require a proxy to be used to access the Internet? If so, you must configure the HTTP_PROXY environment variable before downloading Cypress. Read more: https://on.cypress.io/proxy-configuration

Otherwise, please check network connectivity and try again:

----------

URL: https://download.cypress.io/desktop/9.1.1?platform=linux&arch=x64
Error: socket hang up

----------

Platform: linux-x64 ()
Cypress Version: 9.1.1
```

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-5d3o3f?file=index.js

### Steps to reproduce

Run `cypress install` in the blitz

### Expected behavior

I was hoping this would work.  ;)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 64244581,
  "usedJSHeapSize": 62763389,
  "jsHeapSizeLimit": 4294705152
}
Hash = 731360fb19d99dfc563f19370095b1e3465a14ed
```

**Comment by jrvidal** [comment]
@IanVS Thanks for the report. The install does not complete correctly because the download URL does not return appropriate CORS headers, which is something we can't work around (see for instance https://github.com/stackblitz/webcontainer-core/issues/7 or https://github.com/stackblitz/webcontainer-core/issues/358).

I'll add that, even if it worked or you worked around it (e.g. using an extension to disable CORS), your project might still not work. I'm not sure what you were planning to use `cypress` for, but if it involves using the native binary, it'll simply not work on WebContainer, unfortunately.

I'm closing this for now since I don't think there's anything we can do, but please feel free to comment with more info if appropriate.

**Comment by IanVS** [comment]
Thanks, I was going to show that it didn't have correct typescript types, and the `cypress install` would have scaffolded out some files.  That's good to know that it's not something that can run in stackblitz, thanks for looking into it and responding.
