### ISSUE TITLE
error Command failed with exit code 1

### ISSUE THREAD

**Issue by Rolanddoda** [stackblitz/webcontainer-core#508]
### Describe the bug

I have [this Github repo](https://github.com/Rolanddoda/vue-i18n-next-issue)

What I did was to just import it to the StackBlitz. Dependencies started installing, but then they exited.

### Link to the blitz that caused the error

https://stackblitz.com/github/Rolanddoda/vue-i18n-next-issue

### Steps to reproduce

1. Goto https://stackblitz.com/github/Rolanddoda/vue-i18n-next-issue
2. Wait for the terminal to do the installation
3. Observe the error

### Expected behavior

This was supposed to work

### Screenshots

![image](https://user-images.githubusercontent.com/18482346/147472887-b7866276-c8d0-436c-85eb-e2472a8cae4e.png)

### Platform

```
Browser name  = Chrome 
Full version  = 96.0.4664.93
Major version = 96
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.93 Safari/537.36 OPR/82.0.4227.33
performance.memory = {
  "totalJSHeapSize": 84095440,
  "usedJSHeapSize": 75297888,
  "jsHeapSizeLimit": 4294705152
}
Hash = bc2b78560fa0e6097e7f69d4e820659cab64d2c5
```

**Comment by EricSimons** [comment]
Thanks for reporting this @Rolanddoda - I just repro'd the issue on my machine as well. Seems like every single dependency tarball is giving that same error, but when I try installing the same dependency in fresh node.new project it works fine 🤔 

Our team is taking a deeper look and will circle back once we've gotten to the bottom of it!

**Comment by SamVerschueren** [comment]
After some investigation I noticed that the dependencies are being resolved against `https://registry.npmmirror.com`. I believe we see this as a custom registry and requires auth tokens in order to work. If you remove your `package-lock.json` and run `npm install` to generate a new one, it will work.

Due to the holidays almost everyone is out, so tagging the correct people so we can come back to you in the beginning of January.
cc @jrvidal

**Comment by jrvidal** [comment]
@Rolanddoda This should be fixed now, thanks for the report :tada:
