### ISSUE TITLE
BUG: site using illegal DNS hostnames, will likely cause odd interoperability issues

### ISSUE THREAD

**Issue by dwaite** [stackblitz/webcontainer-core#58]
---
name: Bug report
about: Create a report to help us improve
title: 'site using illegal DNS hostnames, will likely cause odd interoperability issues'
labels: ''
assignees: ''

---

The current deployment will serve up the demo HTTP server with an address such as 

`http-server-rxrywb--8080.local.webcontainer.io`

This is not legal per RFC 952 because of the double hyphen. The original domain name production is:

```BNF
<hname> ::= <name>*["."<name>]
<name>  ::= <let>[*[<let-or-digit-or-hyphen>]<let-or-digit>]
```

Meaning - you cannot include two consecutive hyphens.

(Note this was relaxed later to allow let-or-digit at the start of the name pattern in RFC 1123 )

This is still a legal URI - URI do not mandate the hostname is in DNS so it does not validate against DNS name patterns. However, there are many pieces of software (I discovered this via the iMessage link detector) which will reject such names.

**Comment by KwintenP** [comment]
Hi! 

Thanks for reporting. This is definitely good to know! 
Currently these urls are only used within a single browsing context. The url cannot be called (currently) from anywhere else then the server your browser is running in.

We do have a solution for moving away from this approach so that it could potentially be shareable. We'll take this in regard when the time comes when we implement this feature! 🙏

**Comment by fvsch** [comment]
@dwaite Can you point to a resource that explains how to read the syntax you quoted?
I’m not reading it as forbidding consecutive hyphens, only forbidding hyphens at the start or end of a label.

I also noticed today that Netlify seems comfortable using double hyphens for deploy preview, e.g.
`https://deploy-preview-350--open-ui.netlify.app/`
