### ISSUE TITLE
project was  not pushing  master branch 

### ISSUE THREAD

**Issue by Sohail-TopG** [stackblitz/webcontainer-core#613]
### Describe the bug

whenever i m opening project, data is not pushing to master branch. it just looking like loading but nothing I happening from 1 hour!

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-pytzsd

### Steps to reproduce

1.open project
2. master branch is not saving

### Expected behavior

project should push to master branch 

### Parity with Local

- [ ] I have run the project in my local machine and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 98.0.4758.102
Major version = 98
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81405015,
  "usedJSHeapSize": 76961979,
  "jsHeapSizeLimit": 2172649472
}
Hash = a8f9013f6760f2c4e84edef607d361d3a32b8049
```

**Comment by Nemikolh** [comment]
Hi @Sohail-TopG ! :wave: 

We don't push anything to your main branch when you open a project because there's nothing to push at this point as your project was just opened. I also think the experience for most of our users would be surprising as you typically don't expect your IDE to push commits without any user action.

If you feel like I've missed your feature request, feel free to reopen this ticket and provide more information! 🙂
