### ISSUE TITLE
Vue-2 node-sass error

### ISSUE THREAD

**Issue by EmmyMay** [stackblitz/webcontainer-core#64]
**Describe the bug**
This bug prevents a Vue-2 project which uses node-sass from running. The server fails before it reaches a hundred percent completion.

**Link to the blitz that caused the error**

https://stackblitz.com/edit/node-r5fbve

**To Reproduce**
1. Create a node.js blitz
2. Import a Vue-2 project from GitHub (which has node-sass in its package.json) 
3. Run `npm install`
4. Run `npm run serve`
5. Vue server fails with an error pointing to node-sass/vendor

**Expected behavior**
When `npm run serve is run`, the Vue-2 project is expected to load up.

**Screenshots**

Here is an SC of what the error looks like.
![image](https://user-images.githubusercontent.com/31524469/119242857-5f487680-bb59-11eb-8bc3-43178d7fb602.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version 90

**Additional context**
An Engineer at Stackblitz suggested it was something about WASM. (Idk anything about WASM yet)

**Comment by fvsch** [comment]
Thanks for the report!

Node-sass relies on postinstall scripts that download precompiled x86_64 binaries that won't work in a browser.
It should be possible to migrate from the `node-sass` package to the `sass` package, which ships a JavaScript Sass compiler, and is officially supported by the Sass project.

Here’s a fork with `sass` instead of `node-sass`:
https://stackblitz.com/edit/node-gew6pw

After that, running `npm run serve` seems to work, though some elements don't show up (e.g. some images).
