### ISSUE TITLE
Error in SSR mode of Quasar framework (Vite & Vue)

### ISSUE THREAD

**Issue by Nisgrak** [stackblitz/webcontainer-core#738]
### Describe the bug

The page doesn't load and fire a bunch of infine issue in Console of Page Layout and Quirks Mode
![image](https://user-images.githubusercontent.com/19597708/176763885-9f18a6f6-9b24-4dcc-9203-d02ce74242b9.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/quasarframework-mqszqn?file=package.json

### Steps to reproduce

1. Wait to load the page
2. If nothing is the console make some change in the src/Pages/IndexPage.vue and reload the page

### Expected behavior

See the actual changes and don't crash the tab

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 105.0.0.0
Major version = 105
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 82043356,
  "usedJSHeapSize": 74879820,
  "jsHeapSizeLimit": 4294705152
}
Hash = e40b17327b4f777f5dccacbb86b346b09cdd4176
```

**Comment by Nemikolh** [comment]
Hi @Nisgrak ! :wave: 

Thanks a lot for the bug report. I've been trying your blitz and it seems to be working fine. There's a chance that your issue was fixed recently. I'm going to close this issue but feel free to reopen it if you are still facing the issue or if I missed something :smiley: 

In particular, if you are on Windows and by "crash the tab" you are talking about having Chrome report a `SBOX_FATAL_MEMORY_EXCEEDED` error, I think you are seeing the same as #970. In which case, your only option at this time is to use Firefox.
