### ISSUE TITLE
Non-random preview urls

### ISSUE THREAD

**Issue by malerba118** [stackblitz/webcontainer-core#767]
**Is your feature request related to a problem? Please describe:**

**Background**:

I'd like to build out a mini-app on top of web containers, essentially a file airdropping service where you can go to the same url on two different devices on the same network and then they each spin up a transient server and talk to each other over the local network.

I think i need two things to do this that currently are not possible:

1) have server urls be deterministic (eg: instead of `https://nextjs-8jzaax--3000.local.webcontainer.io` => `https://nextjs-mycustomid--3000.local.webcontainer.io`)
2) be able to resolve a url from outside of the browser that's running the server

An additional third thing i'm not so sure of and would appreciate guidance on is how i'd convert the local url (`https://nextjs-8jzaax--3000.local.webcontainer.io`) to a local network url (and by that i mean something similar to the form of `http://192.168.1.168:3000`)

**Describe the solution you'd like:**
A way to set the url of a preview deterministically and a way to resolve preview urls outside of the browser hosting the web container server

**Describe alternatives you've considered:**
Could always pass the data through a remote server but that's boring

**Additional context:**
Curious if this is on the roadmap and a potential time estimate if it is

**Comment by malerba118** [comment]
I think WebRTC might make this possible today actually, perhaps it's unnecessary to reach for web containers here.

**Comment by Nemikolh** [comment]
Hey @malerba118 ! Thanks for filling this issue.

### Re: server URL deterministic:

This is a bit tricky, the server URLs aren't random until a certain point. When you have a project opened only in one tab then the server URLs are somehow consistent for a same version of the preview.

However if you open that same project in multiple tabs, in order to avoid collision, they have some randomness in them.

### Re: resolve outside the browser:

We have thought about maybe using WebRTC for exactly that use case. See #958

**Comment by jrvidal** [comment]
Closing this as there is nothing actionable for now. You can follow along #958 for WebRTC. Non-random IDs are not really something we can support for now.
