### ISSUE TITLE
Aren't WebContainers now supported in Firefox ?

### ISSUE THREAD

**Issue by SteveALee** [stackblitz/webcontainer-core#770]
### Describe the bug

Created a new project (node express) in Firefox and see the follow at the bottom left

WebContainers for Firefox are in Alpha
Something broken?

I though they were now officially released?

I also had to enable cookies and the docs are for chrome only (I mentioned that in Discord)

### Link to the blitz that caused the error

https://stackblitz.com/edit/express-simple-sazl8v?file=README.md

### Steps to reproduce

Create a project in Firefox, enable cookies

### Expected behavior

no warning for ffx web containers

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 103.0
Major version = 103
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
performance.memory = undefined
Hash = 1f021b18268b32e6c6b2095e039ac8c9f88b0d52
```

**Comment by sulco** [comment]
Hi @SteveALee! We have enabled WebContainers to run in Firefox to the general public and as _officially supported_ you can expect us to work on Firefox-related issues if such come up, but because of the [issues described here](https://developer.stackblitz.com/docs/platform/browser-support/#firefox) we felt it will be a more genuine message to have and to set proper expectations for our users.

Thank you for the question! I hope this answer helped clearing it out – I'm closing the issue, but please reopen for any follow-ups on the topic!
