### ISSUE TITLE
Missing original script path in error message

### ISSUE THREAD

**Issue by sayantan300** [stackblitz/webcontainer-core#784]
### **Description of Bug**
Color is not defined https://stackblitz.com/edit/node-br9gyh

### **Steps to Reproduce**

1. Make a new project and install reejs `npm i reejs` and try to run it via a npm script at package json:
```json
{
"runit": "reejs init"
}
```
2. Run the script as `npm run runit`

### **Expected Behavior**
Reejs Initializing the current project

### **Screenshots/Screencast**
![](https://ren.reeee.ee/ogp/5FAkNJxYH.png)

**Additional Context/Questions**
FYI this framework is mine, and I have tried my best to support stackblitz, but since the error shows from the domain of stackblitz without any context to reejs framework itself, I think this bug is related to stackblitz itself. Still I am not sure though!

**Comment by fvsch** [comment]
I transferred this issue to `webcontainer-core`. I'm also renaming it to change the scope a bit. We probably can't fix the actual error that happens (unless it's a bug on our side, but it doesn't appear to be at this time). But we should print a more informative error, with the path of the file where the original error happened.

**Comment by renhiyama** [comment]
> I transferred this issue to `webcontainer-core`. I'm also renaming it to change the scope a bit. We probably can't fix the actual error that happens (unless it's a bug on our side, but it doesn't appear to be at this time). But we should print a more informative error, with the path of the file where the original error happened.

👍

**Comment by renhiyama** [comment]
Any updates?

**Comment by renhiyama** [comment]
Hey there team, looks like this issue has been fixed, but I cant say the same because... the way import is being handled here, is not great...
![](https://ren.reeee.ee/5G2OlSr_p.png)

(the import file is being read from `/home/projects/[project name]/<file>` ) Can we quickly have a fix that searches for files stored locally instead of trying to import from url? Fyi the file is at https://github.com/rovelstars/reejs/blob/master/server/import.js

**Comment by renhiyama** [comment]
In brief, any suggestions/ideas to fix on absolute file importing?

**Comment by renhiyama** [comment]
```js
import path from "./path.js";
import "../polyfill/process.js";
import { fileURLToPath } from "./url.js";
const __filename = fileURLToPath(import.meta.url);
let __dirname = path.dirname(__filename).split("/").slice(0, -1).join("/");
const originalEmit = process?.emit;
process.emit = function (name, data, ...args) {
    if (
        name === `warning` &&
        typeof data === `object` &&
        data.name === `ExperimentalWarning`
    )
        return false;

    return originalEmit.apply(process, arguments);
};
if (!process.env.REEJS_CUSTOM_DIR) {
    process.env.REEJS_CUSTOM_DIR = __dirname;
}
let dir = fs.existsSync(process.env.REEJS_CUSTOM_DIR) ? process.env.REEJS_CUSTOM_DIR : `${home}/.reejs`;

if (globalThis.fetch) {
    globalThis._fetch = globalThis.fetch;
}
if (!globalThis.fetch) {
    globalThis._fetch = await import(`${dir}/polyfill/fetch.js`);
    globalThis._fetch = globalThis._fetch.default;
}
```
That import with ${dir} seems to cause the error, found at https://github.com/rovelstars/reejs/blob/master/utils/urlimports.js

**Comment by renhiyama** [comment]
@fvsch could you change the name of this issue?

**Comment by d3lm** [comment]
Apart from the error message missing the file information, the issue here is actually that there's an `eval(...)` which uses an import, e.g.
```js
import color from 'some-pkg';

eval(`
  someFunction(color);
`);
```
Notice how it's using `color` inside `eval`. That's unfortunately a current limitation of our ESM implementation. That's why you're seeing `color is not defined`.

**Comment by renhiyama** [comment]
Ah... Imagine those hacks not working here xD

**Comment by renhiyama** [comment]
> Apart from the error message missing the file information, the issue here is actually that there's an `eval(...)` which uses an import, e.g.
> 
> ```js
> import color from 'some-pkg';
> 
> eval(`
>   someFunction(color);
> `);
> ```
> 
> Notice how it's using `color` inside `eval`. That's unfortunately a current limitation of our ESM implementation. That's why you're seeing `color is not defined`.

shouldn't you consider fixing this though? Its one of the basic tokens/letters in js world ;)

**Comment by d3lm** [comment]
This is not as easy to fix as you'd imagine. ESM is a little more complex and the code you're passing to `eval` is a string and we can't analyze strings. A fix for now would be to not use an imported expression inside `eval`. If you really wanted to run the code using a string then I'd suggest to use `new Function()` and pass the variables you need explicitly, e.g.
```js
import color from 'some-pkg';

const fn = new Function('color', `
  someFunction(color);
`);

fn(color);
```
That works as expected and it also allows you to use dynamic imports, whereas with `eval` you can't use that unfortunately. There are some limitations to `eval` which are tricky to solve.

**Comment by renhiyama** [comment]
I think there are some downsides regarding this:
- I need to opt-in/specify the variables to use in that function, whereas eval wont.
- eval can use `sourceMappingURL` comment at the end of the file (or actually the string) and whenever the error happens, the error shows the filename for easy debug... I don't know the equivalent in functions...

And except those problems, I think it would be better to fix the eval implementation in webcontainer. I know and I also have been through bugs/problems that are hard to solve, and just asking the clients/users (referring to users/devs in this case) to use alternative methods doesn't seems like a valid fix ;)
Also it becomes one step backward to the nodejs (v16) compability in webcontainer fyi (no hurt sent here 🙃)

**Comment by d3lm** [comment]
Yes I can totally understand where you’re coming from - the points you’re raising are valid. It is something we need to address. That being said, our roadmap does not prioritize this task at the moment and because of that, I can’t speak to an exact ETA when this will be fixed.

There are certain nitty-gritty details I can’t go into here but for the time being, the workaround I have suggested above can work, at least if you want to run this in WebContainers. Additionally, `sourceMappingURL` as well as `sourceURL` works perfectly fine inside `new Function()`.

We have fixed the original issue with the stack trace not showing the filename where the error originated - we will most likely deploy the fix next week. I am going to let you know when it's deployed.

On a side note, thank you, @renhiyama, for how invested you are in this issue. I hope the workaround will work for you.

**Comment by renhiyama** [comment]
Guess what, Functions did allow using sourceMaps, GG!
Apart from not-so-good-looking codes, a function based implementation seems to work properly.

**Comment by renhiyama** [comment]
Btw why is the nodejs v16 in stackblitz not acting same as the real nodejs version v16.15.0 ?
![image](https://user-images.githubusercontent.com/92968534/188527142-e501f662-da06-4117-9aeb-b41a67730225.png)

This makes my code working in one place and not in another ah..

**Comment by renhiyama** [comment]
Nvm, it works now!

**Comment by renhiyama** [comment]
![image](https://user-images.githubusercontent.com/92968534/188588617-4b0217aa-ef14-4cab-bc6c-ea49cc050a19.png)

**Comment by SamVerschueren** [comment]
Glad this was solved @renhiyama! I'm closing this issue as Ree.js works now. I created an internal ticket for the import in eval error though. Just so we track it internally.
