### ISSUE TITLE
Firefox CORS WebContainer not loading

### ISSUE THREAD

**Issue by geodic** [stackblitz/webcontainer-core#785]
### Describe the bug

Due to strict CORS in Firefox, the WebContainer fails to boot with the error “Cross-Origin Request Blocked”.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-z6rqvv?file=index.js

### Steps to reproduce

1. Go to 'https://stackblitz.com/edit/faker-js-demo?file=index.ts'

### Expected behavior

The WebContainer loads, and you can see the output of the blitz

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

This is the contents of the devtools:
![Devtools content](https://user-images.githubusercontent.com/64704703/187221135-38b0884e-c369-41b3-83ed-29f707ec35c1.png)

### Platform

- OS: Linux (Manjaro Ruah)
- Browser: Firefox Developer Edition
- Version: 104.0b9

**Comment by SamVerschueren** [comment]
This is fixed in the mean time and it does work. However, do note that the image that should be shown can't be loaded because of a missing `CORP` header. One way of fixing this in Firefox is by adding the `crossorigin` attribute to the `img` tag.

https://stackblitz.com/edit/faker-js-demo-88rwwk?file=index.ts
