### ISSUE TITLE
Install dependencies failed with pnpm

### ISSUE THREAD

**Issue by eyelly-wu** [stackblitz/webcontainer-core#790]
### Describe the bug

Install dependencies failed with pnpm，but it's install success after remove pnpm-lock.yaml

### Link to the blitz that caused the error

https://stackblitz.com/edit/i18n-pro-react-demo

### Steps to reproduce

1. open the blitz on the branch of main
2. wait for install dependencies, show log as follow
<img width="1463" alt="image" src="https://user-images.githubusercontent.com/24505069/187922582-75da8bd7-35e3-484b-af4a-bbd1c9136c0d.png">
3. change the branch to StackBlitz，and it's OK，the diff is remove pnpm-locl.yaml
<img width="994" alt="image" src="https://user-images.githubusercontent.com/24505069/187922798-d40a2a58-ee18-459b-bddb-2f206b5ad8ae.png">

### Expected behavior

Install dependencies success with pnpm

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Microsoft Edge
Full version  = 104.0.1293.54
Major version = 104
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.5112.81 Safari/537.36 Edg/104.0.1293.54

// follow don't know

performance.memory = {
  "totalJSHeapSize": 78720264,
  "usedJSHeapSize": 73642520,
  "jsHeapSizeLimit": 4294705152
}
Hash = 4f16907aeb1fd170bcc93609cea1d8dc6ad28342
```

**Comment by SamVerschueren** [comment]
Hi @eyelly-wu. Thanks for reaching out.

So the main problem here is that `npmmirror.com` does not have CORS configured properly. Which is something we need because we still run everything in the browser.

For the regular registry endpoints we intercept those requests and proxy them ourselves. However, we are not aware of the existence of `npmmirror.com`. Can you elaborate a bit more on why you need/use this mirror of npm instead of the regular registry? And is `npmmirror.com` a commonly used mirror?

Kind regards
Sam

**Comment by eyelly-wu** [comment]
@SamVerschueren Thanks a lot，I got it. `npmmirror.com` is a mirror that is suitable for Chinese users to download faster，so it's not necessary, using the default mirror is completely OK.
