### ISSUE TITLE
Dynamic import function with optional parameter object is showing error

### ISSUE THREAD

**Issue by renhiyama** [stackblitz/webcontainer-core#812]
### Describe the bug

Running a dynamic import function with having opts seems to show Syntax Error:
```
[STARTING] Reejs booted up as development mode.
[RELOADER] Looking for file changes...
Error: Unexpected token (68:101)
    at async ESMLoader.import (https://node-br9gyh.w.staticblitz.com/blitz.d0cd7a8669bec74204b2f31e5c2487ab3f6a28b6.js:6:1209283)
    at async i.loadESM (https://node-br9gyh.w.staticblitz.com/blitz.d0cd7a8669bec74204b2f31e5c2487ab3f6a28b6.js:6:246622)
    at async handleMainPromise (https://node-br9gyh.w.staticblitz.com/blitz.d0cd7a8669bec74204b2f31e5c2487ab3f6a28b6.js:6:989292) {
  name: 'SyntaxError'
}
^C
[INFO] Killed Old server...
```

The original source code has:
```js
let mod = await import(`../storage${specifier.slice(0, specifier.lastIndexOf("."))}.js`, opts);
```
in `server/import.js` of `reejs` npm package (can be found at https://github.com/rovelstars/reejs) too.

FYI: I am the author of reejs, and I am willing to solve this problem if there's any requirements/suggestions to a possible fix.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-br9gyh?file=index.js

### Steps to reproduce

1. Install via `npm i`
2. run `node ./index.js`
Errors out:
```
[STARTING] Reejs booted up as development mode.
​ [RELOADER] Looking for file changes...
​         let mod = await import(`../storage${specifier.slice(0, specifier.lastIndexOf("."))}.js`, opts);
                                                                                                      ^
(anonymous) @ blitz.d0cd7a8669bec7…487ab3f6a28b6.js:15
​ [INFO] Killed Old server...
```

### Expected behavior

Should start up properly...

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

- OS: [e.g. macOS, Windows, Linux]
- Browser: [e.g. Chrome, Safari, Firefox]
- Version: [e.g. 91.1]

**Comment by renhiyama** [comment]
Also, I don't think this is a problem with js itself, devtools can run this piece of code just fine:
```js
await import("https://esm.sh/preact",{test: "object"});
```

**Comment by d3lm** [comment]
Hey 👋 Thansk for the report!

Yes, this is not an issue with JS itself but there is something going wrong somewhere, cause normally that syntax should be supported. If you'd run the following in your `index.js`:

```
const fs = await import('fs', {});
console.log(fs);
```

then that works just fine. I am not sure what the issue is and we need to investigate. We'll be tracking this issue internally as well.

**Comment by renhiyama** [comment]
@d3lm any updates? I have updated a lot of code, still it seems you can't dynamically import json files.
https://stackblitz.com/edit/stackblitz-starters-rnq6nn?file=ree.js

**Comment by d3lm** [comment]
Hey, no we haven't had a chance to look into yet. We'll post an update if we there's any progress.

**Comment by kirjavascript** [comment]
Hi! After adding compatibility for the import syntax used here and upgrading to node 16.20.0 to support JSON modules without a flag, reejs seems to be working;

https://stackblitz.com/edit/reejs-0-9-12-4wqbsu?file=ree.js

(I had to delete the `package-lock.json`, otherwise the specified dependencies complain about a lack of global `fetch`)

Feel free to open another issue if you are still having trouble!
