### ISSUE TITLE
pnpm install ....error

### ISSUE THREAD

**Issue by ManKeung** [stackblitz/webcontainer-core#824]
### Describe the bug

![image](https://user-images.githubusercontent.com/24784956/194766432-b4234e7e-63b6-41c2-a40d-e116fa1ab78b.png)

### Link to the blitz that caused the error

https://stackblitz.com/github/mankeung/mk-vue?terminal=dev

### Steps to reproduce

pnpm install

### Expected behavior

Normal startup

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 81876578,
  "usedJSHeapSize": 71886522,
  "jsHeapSizeLimit": 4294705152
}
Hash = c3f3eab0760382367e86f2a862c18516376c36f4
```

**Comment by jrvidal** [comment]
:wave: Thanks for the report. This is somewhat expected, as we can't work around CORS limitations in the browser. We only support the default NPM registry.

We have plans to support more registries in the future, but I can't offer a concrete timeline.

**Comment by d3lm** [comment]
Hey 👋 We have shipped [StackBlitz Teams](https://developer.stackblitz.com/teams/what-is-stackblitz-teams) which allows you to use custom / private registries while at the same time being more secure that just using a `.npmrc` which is what we don't recommend because that file gets uploaded. With StackBlitz Teams you can configure tokens per registry via the dashboard and they will be stored securely.

I am going to close this one. If you have questions, feel free to respond to this issue anyways.
