### ISSUE TITLE
I can't see my son file.

### ISSUE THREAD

**Issue by Rofound** [stackblitz/webcontainer-core#855]
### Describe the bug

Import all project files, but son files not see.

### Link to the blitz that caused the error

https://stackblitz.com/edit/node-wj1xmk?file=src%2Frouter%2Findex.js

### Steps to reproduce

1.open directory src/views/TotalReport.
2.src/views/TotalReport is null directory.

### Expected behavior

Import project files. view all files.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/26542093/196312167-f6339aaa-cc67-4b05-ae29-55bddfc9585f.png">

### Platform

```
Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 106243586,
  "usedJSHeapSize": 96656946,
  "jsHeapSizeLimit": 4294705152
}
Hash = 8710b01cd3456444b4ea0bc080c4276768dc0bc7
```

### Additional context

Good lucky

**Comment by SamVerschueren** [comment]
Hi @Rofound. What happens if you try to upload your `son` file to that directory? Because a `son` file appears to be a binary file, you can only upload them if you have a paid StackBlitz account. That might be the reason why after a refresh you don't see them.

Normally if you drag them in that directory, it should show a message regarding binary files and paid membership.

Is this project on GitHub somewhere? If it is, try opening it by prefixing the GitHub URL to the project with `pr.new`. You should end up in our Codeflow IDE which is more powerful but is entirely git-based. Which means that changes have to be committed back to git.
