### ISSUE TITLE
Corrupt terminal text in Brave

### ISSUE THREAD

**Issue by john-oc** [stackblitz/webcontainer-core#874]
### Describe the bug

When opening a repo in Brave, all characters in the terminal window have their right-hand side cut off 

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/john-oc/primevue

### Steps to reproduce

1. Simply load the repo in Brave

### Expected behavior

Terminal text should be legible,

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

![codeflow corrupt terminal in brave](https://user-images.githubusercontent.com/5717697/197387171-f8b9528e-854d-4b0f-b2bf-4a1aa4cbb20e.jpg)

### Platform

```
Version = 1.67.0
Hash = 771d21865841b49ec9d3de318b49ea649c509949
WebContainer = dfae8564d35fe429a0bab219bd7d77341f3ec782

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 216364230,
  "usedJSHeapSize": 116522554,
  "jsHeapSizeLimit": 2172649472
}
```

**Comment by SamVerschueren** [comment]
Hi @john-oc, thanks for reporting 🙏 !

Apparently this is an issue with xterm.js and Brave because of Brave's fingerprinting detection. You can find more information right here https://github.com/xtermjs/xterm.js/issues/3492.

After changing the following setting, it does seem to render correctly

![image](https://user-images.githubusercontent.com/1913805/197523717-93d11f43-b740-46b7-9c60-bd9f801171ff.png)

We'll probably make this the default behaviour if this is showing the best results on every browser.

**Comment by SamVerschueren** [comment]
This is now fixed. Thanks for reporting 🙏 

![image](https://user-images.githubusercontent.com/1913805/197762363-e8e1d9e4-bd26-450e-9b72-c13a68c991bb.png)
