### ISSUE TITLE
Yarn install fails on @webassembly/deasync but npm install works fine

### ISSUE THREAD

**Issue by jgentes** [stackblitz/webcontainer-core#875]
### Describe the bug

`npm install` works fine, but yarn fails. Deleting the `yarn.lock` file doesn't seem to help.
```
yarn install v1.22.19
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error An unexpected error occurred: "Failed to fetch dependencies:
- @webassembly/deasync@[object Object]".
```
See `yarn-error.log` in the repo for more error details.

Thanks! :)

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/jgentes/mixpoint

### Steps to reproduce

Run `yarn` or `yarn install` in the root folder.

### Expected behavior

`@webassembly/deasync` should install properly as it does with npm.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.67.0
Hash = 771d21865841b49ec9d3de318b49ea649c509949
WebContainer = dfae8564d35fe429a0bab219bd7d77341f3ec782

Browser name  = Chrome
Full version  = 106.0.0.0
Major version = 106
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/106.0.0.0 Safari/537.36 Edg/106.0.1370.47
performance.memory = {
  "totalJSHeapSize": 92801821,
  "usedJSHeapSize": 75241185,
  "jsHeapSizeLimit": 4294705152
}
```

**Comment by SamVerschueren** [comment]
Hey @jgentes, thanks for reporting. We had an issue with `yarn` which is now addressed and deployed to production.

The project however is unable to boot because of some issue with `web-audio-beat-detector`. It's also an issue on local. Remix seems to use a polyfill for `Blob`, so when a [Worker is created in web-audio-beat-detector](https://github.com/chrisguttandin/web-audio-beat-detector/blob/master/src/module.ts), it will do `URL.createObjectURL` which checks if the provided object is a `Blob`. It's not a real Blob, because it misses some unique symbol which just can't be polyfilled. Anyways, if this is supposed to work with Remix, I think you have to report it upstream.

```js
TypeError: The "obj" argument must be an instance of Blob. Received an instance of Blob
    at new NodeError (node:internal/errors:371:5)
    at Function.createObjectURL (node:internal/url:960:13)
    at /Users/sam/Documents/vue3/remix-run/mixpoint/node_modules/web-audio-beat-detector/build/es5/bundle.js:13:16
    at /Users/sam/Documents/vue3/remix-run/mixpoint/node_modules/web-audio-beat-detector/build/es5/bundle.js:2:65
    at Object.<anonymous> (/Users/sam/Documents/vue3/remix-run/mixpoint/node_modules/web-audio-beat-detector/build/es5/bundle.js:5:3)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1157:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
```

**Comment by jgentes** [comment]
Thanks Sam! Yes, I'm familiar with the `createObjectURL` issue and have a
fix in for that. Just wanted to report the Yarn issue, and I'm glad to hear
you've worked it out so quickly :)

-James
