### ISSUE TITLE
vue nativescrript starter not working on samsung tab s7 fe 

### ISSUE THREAD

**Issue by sombriks** [stackblitz/webcontainer-core#925]
### Describe the bug

i am trying to create a nativescript vue project using my tablet but it's not working.
trying the same on mac/windows/linux works fine.

i am using google chrome on android and pc.

### Link to the blitz that caused the error

https://stackblitz.com/edit/nativescript-stackblitz-templates-fndgxh?file=app%2Fcomponents%2FHome.vue&title=NativeScript%20Starter%20Vue

### Steps to reproduce

see video
https://twitter.com/sombriks/status/1605331977745350656

### Expected behavior

i want to use mobile to develop mobile

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 108.0.0.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Linux; Android 12; SM-T735) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 84290969,
  "usedJSHeapSize": 66009733,
  "jsHeapSizeLimit": 1098907648
}
Hash = 6ebe18b1e1db1833797e3e4eb6ff802c375ee61b
```

**Comment by SamVerschueren** [comment]
Hi @sombriks, thanks for reporting. Does this only happen for the Vue Starter, or for every NativeScript project?

Would it be possible to get a screenshot of the Chrome Devtools on that device? It would really help if we know the exact error that's causing this. I can't seem to be able to reproduce in an Android Emulator, but an emulator is always a bit different so don't want to rely too much on that.

**Comment by sombriks** [comment]
Hello @SamVerschueren !

Here goes the screeshot from a nativescript-react starter:

![Screen Shot 2022-12-22 at 8 58 35 PM](https://user-images.githubusercontent.com/556695/209245061-51fe68cf-b748-4503-887f-211c4b9c63f3.png)

It gets the same behavior seen in nativescrit-vue starter.

the vanilla js starter however behaves differently, it never ends the loading phase.

![Screen Shot 2022-12-22 at 9 02 59 PM](https://user-images.githubusercontent.com/556695/209245383-21acebc1-b9ac-4417-a356-b3531c8dd6c7.png)

**Comment by sombriks** [comment]
that final prepeating warning is something like this:

`The resource https://w-credentialless.staticblitz.com/yarn_index.6ebe18b1e1db1833797e3e4eb6ff802c375ee61b was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloa`

**Comment by fvsch** [comment]
Hi @sombriks. We could not reproduce on the Android devices we have so far.

The warning about preloaded resources should not be an issue. (It signals a performance optimization we might do on our side, but shouldn't affect you here.)

From the top of my mind, there are two things I'd like to check:

1. I'm seeing an entry in the Issues panel titled "Specify a Cross-Origin Resource Policy to prevent a resource from being blocked". Could you expand this issue and report back what resource(s) are being blocked?

2. To figure out if an issue might be caused by non-default browser settings or extensions, we usually want to test on the same machine with a blank Chrome profile. On desktop Chrome that's easy to do (you can start a Guest session), but on Android it's more limited. The best way to test with a brand new profile (outside of nuking all your settings and data in your main profile, which we don’t want) might be to download the Chrome Beta app from the Play Store, and use it without connecting a Google account or changing any settings. That would be testing Beta instead of the Stable release, but should probably be fine.

**Comment by sombriks** [comment]
Hello @fvsch !

I've followed your tip and tried native browser for this samsung tablet.

Turns out i **do** can use this android tablet to develop android via stackblitz and nativescript!

This is the screenshot when i inspect samsung browser instead of chrome:
![Captura de tela de 2022-12-24 15-06-04](https://user-images.githubusercontent.com/556695/209447108-5481cd71-7f2c-465f-be75-5485b05cee9b.png)

Screenshot from device itself:
![Screenshot_20221224_150553_Samsung Internet](https://user-images.githubusercontent.com/556695/209447163-c5deaf4a-3d0c-415d-bcd7-b0b453a5859b.jpg)

I can pair my phone with tablet via qr-code and see my app :-)

This is a game changer.

Regarding why chrome refuses to work properly i need more time to dig it up, but seeing it work properly with the out-of-the-box samsung browser solves my issue.

Thanks for the guidance and happy holidays!
