### ISSUE TITLE
Exposing ports on Android/Firefox not working, with confusing error

### ISSUE THREAD

**Issue by hybridherbst** [stackblitz/webcontainer-core#942]
### Describe the bug

From the docs (https://developer.stackblitz.com/docs/platform/browser-support/) platform support doesn't become quite clear. Seems Chrome on Android is not supported, but I then tried Firefox and web containers boot up, yay!

I started the vite+vue template,
Went to "Ports",
Clicked the port,
Was greeted by an error message:
`No server listening on port 5173. Try:
    Opening vitejsvitef5mn2y-0lya on StackBlitz` (bug?)
Clicking on that message brings me to a 404 page:
https://stackblitz.com/edit/vitejsvitef5mn2y-0lya

While I understand the tech may not be ready for mobile use, the messaging (both for webcontainers not booting on Chrome Android and the ports not working) could be more clear.

I've tried a bunch of other templates with the same results.

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-f5mn2y?file=index.html,package.json&terminal=dev

### Steps to reproduce

- I started the vite+vue template,
- Went to "Ports",
- Clicked the port,
- Was greeted by an error message:
  `No server listening on port 5173. Try:
    Opening vitejsvitef5mn2y-0lya on StackBlitz` (bug?)
- Clicking on that message brings me to a 404 page:
  https://stackblitz.com/edit/vitejsvitef5mn2y-0lya

### Expected behavior

Either functionality is working or reasonable error messages would be desired over the current state of unclear errors

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Firefox
Full version  = 108.0
Major version = 108
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Android 10; Mobile; rv:108.0) Gecko/108.0 Firefox/108.0
performance.memory = undefined
Hash = 8565d4cc02cd18bee77df4dd35a4cbd621004602
```

**Comment by fvsch** [comment]
Thanks for the report @hybridherbst!

@sylwiavargas It looks like the [WebContainers browser support doc page](https://developer.stackblitz.com/platform/webcontainers/browser-support) is slightly outdated. In particular, the `tl;dr` restricts support to desktop browsers, but we do run WebContainers in Chrome and Firefox on Android (not on iOS, because all iOS browsers are Safari). We probably want to coordinate with the WebContainers team to reword that paragraph.

Re. why the preview page is not served on Firefox or Chrome for Android, @hybridherbst can you give more information about the specific browsers you've tested (including browser versions)?

At least on desktop browsers, we've seen issues or limitations with serving web pages from a Node process when the browser configuration restricts access to some features, including:

- Service Workers
- Third Party Cookies (which also disables SharedArrayBuffer in some browsers)

So the underlying issue might be a Chrome-on-Android vs Chrome-desktop issue, a Firefox-on-Android vs Firefox-desktop issue; or it can be a your-config-on-Chrome-on-Android vs your-config-on-Chrome-desktop issue or a your-config-on-Firefox-on-Android vs your-config-on-Firefox-desktop issue.

**Comment by hybridherbst** [comment]
Thanks @fvsch for following up –
**Device:** Xiami Mi 9, Android 10
**Firefox:** 108.2.0 – above link works, WebContainers load, but port can't be exposed (see errors above)
**Chrome:** 109.0.5414.86 – WebContainers don't load (for none of the templates I tried)

Happy to understand more about how I can get closer to giving you the information you need.

**Comment by d3lm** [comment]
Hey! Thanks for reporting this issue. There is currently an issue with Firefox and opening ports in separate tabs due to [storage paritioning](https://developer.chrome.com/docs/privacy-sandbox/storage-partitioning/). We are aware of this issue and already working on a fix. We'll keep you posted.

**Comment by Nemikolh** [comment]
Hey! We now have full support for running previews in a separate tab in Firefox! :tada: 

We're planning to write a blog post about this in the near future to explain what it involved and also the UX difference between browsers implementing Storage Partitioning (also called State partitioning) and those which do not. CC @sylwiavargas
