### ISSUE TITLE
No Safari Support !!!!!!!!

### ISSUE THREAD

**Issue by ctkjose** [stackblitz/webcontainer-core#949]
### Describe the bug

Have you guys tried to support Safari? I'll be a Karen for a minute and throw a tantrum but supporting Safari is not that hard at all...

### Link to the blitz that caused the error

https://stackblitz.com/github/twbs/examples/tree/main/sass-js-esm?file=index.html

### Steps to reproduce

Open site in any recent Safari...

### Expected behavior

Use a website in my default browser...

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Safari
Full version  = 15.4
Major version = 15
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.4 Safari/605.1.15
performance.memory = undefined
Hash = f46762818326be16a78de429bec3a3775ca1af32
```

**Comment by SamVerschueren** [comment]
Hi @ctkjose. Thanks for reaching out. The problem here is that we're not building something that has been done many times before.

> I'll be a Karen for a minute and throw a tantrum but supporting Safari is not that hard at all...

You are absolutely right here. Supporting Safari is not hard at all, it's actually impossible today... If you had clicked the link to open the documentation and scrolled down a bit, [there's a section on why Safari does not work today](https://developer.stackblitz.com/platform/webcontainers/browser-support#safari).

Do we want all of this to work in Safari? Of course we want that, because that would also mean that it works on iPad/iPhone and what not. But reality is that Safari just doesn't implement all the features we need. Before you start talking about polyfilling everything. Nope, impossible.
