### ISSUE TITLE
Visual isn't showing 

### ISSUE THREAD

**Issue by kuliksarra** [stackblitz/webcontainer-core#950]
### Describe the bug

It is not showing the visuals of my code and is just saying booting webcontainer

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-uwjsh8?file=index.html

### Steps to reproduce

just look to the right i guess

### Expected behavior

explanation and fixing of why its not showing

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Screenshots

<img width="784" alt="image" src="https://user-images.githubusercontent.com/97130757/214921012-462f662e-fd5d-47dd-8353-04687018cf7f.png">

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87173166,
  "usedJSHeapSize": 82095922,
  "jsHeapSizeLimit": 2172649472
}
Hash = 306c160b7022afc5d2e8a4fd7c8489d8cc92c364
```

**Comment by SamVerschueren** [comment]
Hi @kuliksarra. You have to run a command in order to start the project, just as you would do locally. The right side just tells you that WebContainer booted. Maybe we should be more clear and put a "call to action" there to start the project.

I noticed you don't have any `package.json` or any way to start the project. You could use [lite-server](https://www.npmjs.com/package/lite-server) by running `npx lite-server` in the terminal.

![image](https://user-images.githubusercontent.com/1913805/215041508-e352d32a-d610-48d1-bb21-e8271d6cef29.png)

**Comment by kuliksarra** [comment]
Thank you!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
