### ISSUE TITLE
Browser window is not loading localhist:4200

### ISSUE THREAD

**Issue by Rohith47** [stackblitz/webcontainer-core#956]
### Describe the bug

After Running npm start, browser window is not opening.

### Link to the blitz that caused the error

https://stackblitz.com/edit/angular-bpx2g6?file=.stackblitzrc

### Steps to reproduce

Run npm start

### Expected behavior

Browser window loading http://localhost:4200 should be visible

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 109.0.0.0
Major version = 109
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36
performance.memory = {
  "totalJSHeapSize": 87362937,
  "usedJSHeapSize": 70638805,
  "jsHeapSizeLimit": 4294705152
}
Hash = 522185bb0134fb732ed5ecb9887332d7f888ce1b
```

**Comment by SamVerschueren** [comment]
Hi @Rohith47, thanks for creating this issue. When you run `npm start`, don't you see the preview window on the right?

![image](https://user-images.githubusercontent.com/1913805/216299620-264f875e-16b8-4be2-9aea-b002e711ce39.png)

Do notice that the URL is not `localhost:4200`. The reason is that browsers don't allow running servers on the local machine. This means that we can spin up a server inside your browser, and you can also open that URL in a separate browser tab (see the `Open in new tab` button in the top right), but it's not reachable from `localhost:4200`. Do notice that that URL is only reachable from your own machine (and only from within the same browser that you started the server in).

Hopefully this provides you with enough information. I'll close the issue, let me know if there's anything else I can help you with.
