### ISSUE TITLE
BUG: `time ...` does not work

### ISSUE THREAD

**Issue by connorjclark** [stackblitz/webcontainer-core#98]
---
name: Bug report
about: Create a report to help us improve
title: ''
labels: ''
assignees: ''

---

**Describe the bug**

Type in terminal:

```
> time echo 123
e.Assigns is not iterable
```

**Version of webcontainer**
Hash: 7286dbe8d47d3473cde7be488b7d048fb59b05f2

**Desktop (please complete the following information):**
Browser name  = Chrome 
Full version  = 90.0.4430.212
Major version = 90
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
performance.memory = {
  totalJSHeapSize: 83993002,
  usedJSHeapSize: 81515234,
  jsHeapSizeLimit: 4294705152
}

**Comment by SamVerschueren** [comment]
Hi @connorjclark! Thanks for this issue. You are correct, the `time` command is not implemented right now so that's the reason why it doesn't work. We are planning at adding more commands in the near future but can't give you an exact estimate.

The terminal does give you the number of seconds something ran, only if longer than 5 seconds though, so it's definitely not as accurate as the `time` command.

![image](https://user-images.githubusercontent.com/1913805/119701917-2b20ce80-be55-11eb-9e23-0dc6dfc27170.png)

**Comment by connorjclark** [comment]
ah, I didn't notice that, thanks for the tip!

**Comment by SamVerschueren** [comment]
This is fixed now. You can now run `time npm install` and it will show you how long it took.
