### ISSUE TITLE
error when opening react-ts in vite

### ISSUE THREAD

**Issue by XexT** [stackblitz/webcontainer-core#994]
### Describe the bug

![image](https://user-images.githubusercontent.com/92929085/223892358-a7ff5f63-a05f-4552-94c7-ddc7a97c9948.png)

### Link to the blitz that caused the error

https://stackblitz.com/edit/vitejs-vite-zkvavy?file=src%2Fmain.tsx

### Steps to reproduce

Just Open

### Expected behavior

error

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Browser name  = Chrome
Full version  = 110.0.0.0
Major version = 110
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36 Edg/110.0.1587.63
performance.memory = {
  "totalJSHeapSize": 76210586,
  "usedJSHeapSize": 63105946,
  "jsHeapSizeLimit": 4294705152
}
Hash = d4a32cb71496f1cb7595ed7c8471aaa3b79d22fc
```

**Comment by zhatongning** [comment]
可能是资源被墙了（maybe it's not problem with webContainer, you can't fetch the resource.）

**Comment by SamVerschueren** [comment]
Hi @Ucely 👋 . The problem here is the `WebAssembly.instantiate() Out of Memory` error. Is it possible you have multiple StackBlitz projects open at the same time? There's more information [here in our docs regarding Codeflow](https://developer.stackblitz.com/codeflow/working-in-codeflow-ide#out-of-memory-error) about this error.

If you had multiple StackBlitz WebContainer projects open in different browser tabs, try closing some of them and refresh the page.

**Comment by XexT** [comment]
Yeah, it's probably because of the multi-tabs opened. Many thanks!
