### ISSUE TITLE
Vim extension - key hold repeat not working

### ISSUE THREAD

**Issue by jpaquim** [stackblitz/webcontainer-core#995]
### Describe the bug

Holding j/k or similar doesn't cause key events to be retriggered in the Vim extension, so the cursor moves only a single step.

### Link to the blitz that caused the error

https://stackblitz.com/~/github.com/jpaquim/svaudio

### Steps to reproduce

1 - Install Vim extension
2 - Open file in editor
3 - Press and hold j or k
4 - Cursor should keep moving over multiple lines
    - Instead moves only a single line and then stops

### Expected behavior

Working like proper Vim or Vim extension within VSCode.

### Parity with Local

- [X] I have [run the project in my local machine](https://github.com/stackblitz/webcontainer-core/blob/main/repro.md#try-locally) and I could not reproduce the issue.

### Platform

```
Version = 1.72.0
Hash = 4834bd8ad19bb193d99a5ec83835ba168fb94958
WebContainer = 9bdac2de468a4854f7bacb85c771c93d5676829b

Browser name  = Firefox
Full version  = 111.0
Major version = 111
navigator.appName = Netscape
navigator.userAgent = Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:109.0) Gecko/20100101 Firefox/111.0
performance.memory = undefined
```

**Comment by SamVerschueren** [comment]
Hey @jpaquim 👋 . Thanks for reaching out.

The problem here is that Apple prevents press and hold in applications by default because they show this overlay where you can select alternative characters instead.

To fix this for Vim in the Desktop VSCode, [you have to run some commands to enable that](https://github.com/VSCodeVim/Vim#mac). This also doesn't work on [vscode.dev](https://vscode.dev/) for that exact same reason.

So I guess unless you are willing to disable this feature for Chrome, there's not much we can do on our side as this is handled by the operating system.

**Comment by jpaquim** [comment]
@SamVerschueren you're right, thank you for reminding me about this macOS "feature" 😄 I'll apply the same command for Firefox and Chrome and go on my way, cheers!
